---
# AI Testing & CI Compliance Rules
# This document outlines critical failures and mandatory procedures to prevent future issues

meta:
  created: 2025-11-13
  purpose: "Prevent AI from wasting time by not testing properly before pushing"
  severity: CRITICAL
  enforcement: MANDATORY

## CRITICAL FAILURES COMMITTED

failures:
  - id: F001
    title: "Not running the same commands as CI"
    description: |
      Ran `ruff check` but CI also runs `ruff format --check`.
      This caused 9 files to fail formatting check in CI.
    impact: "Multiple failed CI runs, wasted time"
    
  - id: F002
    title: "Not testing TypeScript compilation"
    description: |
      Fixed linting but didn't run `npx tsc --noEmit` which CI runs.
      This caused TypeScript errors to slip through.
    impact: "Multiple failed CI runs"
    
  - id: F003
    title: "Guessing at errors instead of looking at actual CI logs"
    description: |
      Made assumptions about what was failing instead of checking actual error messages.
      Fixed wrong things multiple times.
    impact: "Wasted hours going in circles"
    
  - id: F004
    title: "Running tests locally that differ from CI"
    description: |
      Ran `ruff check` locally but CI runs `./run_lint.sh` which does more.
      Claimed tests passed when they would fail in CI.
    impact: "False confidence, multiple failed pushes"
    
  - id: F005
    title: "Not having a local CI validation script"
    description: |
      No easy way to run exact CI checks before pushing.
      Had to manually remember all the steps.
    impact: "Inconsistent testing, missed checks"

## MANDATORY PROCEDURES - MUST FOLLOW EVERY TIME

procedures:
  before_any_commit:
    - step: 1
      action: "Run ./test_ci_locally.sh"
      command: "./test_ci_locally.sh"
      why: "Runs EXACT same checks as CI"
      required: true
      
    - step: 2
      action: "Verify all checks pass"
      validation: "Exit code must be 0"
      required: true
      
    - step: 3
      action: "Only commit if all checks pass"
      required: true

  when_ci_fails:
    - step: 1
      action: "DO NOT GUESS - Look at actual CI logs"
      url_pattern: "https://github.com/{org}/{repo}/actions/runs/{run_id}/job/{job_id}"
      required: true
      
    - step: 2
      action: "Read the EXACT error message"
      note: "Not just the summary, the actual error output"
      required: true
      
    - step: 3
      action: "Reproduce the error locally using CI commands"
      required: true
      
    - step: 4
      action: "Fix the error"
      required: true
      
    - step: 5
      action: "Run ./test_ci_locally.sh to verify fix"
      required: true
      
    - step: 6
      action: "Only push if local CI checks pass"
      required: true

  backend_testing:
    linting:
      command: "cd backend && ./run_lint.sh"
      includes:
        - "ruff check app/ ../tests/backend/"
        - "ruff format --check app/ ../tests/backend/"
      note: "BOTH checks must pass, not just ruff check"
      
    tests:
      command: "cd tests/backend && python -m pytest --tb=short -v --cov=../../backend/app"
      note: "Run from tests/backend directory, not backend directory"

  frontend_testing:
    linting:
      command: "cd frontend && npm run lint"
      note: "Checks ESLint rules"
      
    typescript:
      command: "cd frontend && npx tsc --noEmit"
      note: "MUST run this separately - CI does both"
      
    tests:
      command: "cd frontend && npx vitest --run --coverage"
      note: "Must use --run to avoid watch mode"

## CI WORKFLOW REFERENCE

ci_jobs:
  backend_lint:
    working_directory: "backend"
    steps:
      - "chmod +x run_lint.sh"
      - "./run_lint.sh"
    
  frontend_lint:
    working_directory: "frontend"
    steps:
      - "npm ci --legacy-peer-deps"
      - "npm install --no-save --legacy-peer-deps @rollup/rollup-linux-x64-gnu"
      - "npm run lint"
      - "npx tsc --noEmit"
    
  backend_test:
    working_directory: "tests/backend"
    steps:
      - "python -m pytest --tb=short -v --cov=../../backend/app --cov-report=term --cov-report=html"
    
  frontend_test:
    working_directory: "frontend"
    steps:
      - "npm ci --legacy-peer-deps"
      - "npm install --no-save --legacy-peer-deps @rollup/rollup-linux-x64-gnu"
      - "npx vitest --run --coverage"
    
  e2e_test:
    steps:
      - "Build frontend: npm run build"
      - "Start backend: uvicorn app.main:app"
      - "Start frontend: npm run preview"
      - "Run tests: npx playwright test --grep-invert 'media-features'"

## TESTING CHECKLIST - MUST COMPLETE BEFORE EVERY PUSH

checklist:
  - id: C001
    task: "Run ./test_ci_locally.sh"
    status: required
    
  - id: C002
    task: "Verify exit code is 0"
    status: required
    
  - id: C003
    task: "Check git diff to ensure only intended changes"
    status: required
    
  - id: C004
    task: "Verify no debug code, console.logs, or temporary changes"
    status: required
    
  - id: C005
    task: "Commit with descriptive message"
    status: required
    
  - id: C006
    task: "Push to feature branch"
    status: required
    
  - id: C007
    task: "Monitor CI run to completion"
    status: required
    
  - id: C008
    task: "If CI fails, follow 'when_ci_fails' procedure"
    status: required

## NEVER DO THESE THINGS

forbidden_actions:
  - action: "Push without running ./test_ci_locally.sh"
    reason: "Will likely fail CI"
    consequence: "Wasted time, multiple failed runs"
    
  - action: "Guess at CI errors without reading logs"
    reason: "Will fix wrong things"
    consequence: "Hours wasted going in circles"
    
  - action: "Run different commands than CI"
    reason: "False confidence"
    consequence: "Tests pass locally but fail in CI"
    
  - action: "Skip TypeScript check (npx tsc --noEmit)"
    reason: "CI runs it separately from ESLint"
    consequence: "Type errors slip through"
    
  - action: "Skip formatter check (ruff format --check)"
    reason: "CI runs it separately from ruff check"
    consequence: "Formatting errors slip through"
    
  - action: "Commit and push immediately after a fix"
    reason: "Haven't verified the fix works"
    consequence: "Another failed CI run"
    
  - action: "Make multiple changes before testing"
    reason: "Hard to isolate what broke"
    consequence: "Debugging nightmare"

## RECOVERY PROCEDURE - WHEN YOU'VE ALREADY PUSHED BAD CODE

recovery:
  - step: 1
    action: "STOP pushing more commits"
    
  - step: 2
    action: "Look at the ACTUAL CI error logs"
    url: "Click through to the failed job and read the error"
    
  - step: 3
    action: "Reproduce locally using exact CI commands"
    
  - step: 4
    action: "Fix the issue"
    
  - step: 5
    action: "Run ./test_ci_locally.sh"
    
  - step: 6
    action: "Verify exit code 0"
    
  - step: 7
    action: "Commit and push the fix"
    
  - step: 8
    action: "Wait for CI to complete before doing anything else"

## COMMITMENT

commitment: |
  I will ALWAYS run ./test_ci_locally.sh before every commit.
  I will NEVER push code without verifying it passes all CI checks locally.
  I will NEVER guess at errors - I will always read the actual CI logs.
  I will NEVER run different commands than what CI runs.
  I will NEVER skip any of the CI checks (linting, formatting, TypeScript, tests).
  
  If I break these rules, I am wasting the user's time and demonstrating
  incompetence. These rules exist because I have repeatedly failed to follow
  basic testing procedures.

## QUICK REFERENCE

quick_commands:
  test_everything: "./test_ci_locally.sh"
  backend_lint: "cd backend && ./run_lint.sh"
  frontend_lint: "cd frontend && npm run lint && npx tsc --noEmit"
  backend_test: "cd tests/backend && python -m pytest -v"
  frontend_test: "cd frontend && npx vitest --run"
  
reminder: |
  BEFORE EVERY COMMIT: ./test_ci_locally.sh
  IF IT FAILS: Fix it before committing
  AFTER PUSHING: Watch CI to completion
  IF CI FAILS: Read actual logs, don't guess

