import React, { createContext, useContext, useState, useEffect, useMemo, useCallback, ReactNode } from 'react';

// Theme definition interface
export interface Theme {
  id: string;
  name: string;
  description?: string;
  colors: {
    // Background colors
    bgPrimary: string;
    bgSecondary: string;
    bgTertiary: string;
    bgHover: string;
    
    // Text colors
    textPrimary: string;
    textSecondary: string;
    textTertiary: string;
    
    // Border colors
    borderPrimary: string;
    borderSecondary: string;
    
    // Accent colors
    accent: string;
    accentHover: string;
    accentText: string;
    
    // Semantic colors
    success: string;
    error: string;
    warning: string;
    info: string;
    
    // Card colors
    cardBg: string;
    cardBorder: string;
    cardShadow: string;
  };
}

// Predefined themes
export const themes: Record<string, Theme> = {
  amber: {
    id: 'amber',
    name: 'Amber Glow',
    description: 'Warm golden amber',
    colors: {
      bgPrimary: '#fffbeb',
      bgSecondary: '#fef3c7',
      bgTertiary: '#fde68a',
      bgHover: '#fef3c7',
      textPrimary: '#78350f',
      textSecondary: '#92400e',
      textTertiary: '#b45309',
      borderPrimary: '#fcd34d',
      borderSecondary: '#fbbf24',
      accent: '#f59e0b',
      accentHover: '#d97706',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#3b82f6',
      cardBg: '#ffffff',
      cardBorder: '#fcd34d',
      cardShadow: 'rgba(245, 158, 11, 0.2)',
    },
  },
  
  amethyst: {
    id: 'amethyst',
    name: 'Amethyst',
    description: 'Rich amethyst purple',
    colors: {
      bgPrimary: '#3b0764',
      bgSecondary: '#581c87',
      bgTertiary: '#6b21a8',
      bgHover: '#581c87',
      textPrimary: '#e9d5ff',
      textSecondary: '#d8b4fe',
      textTertiary: '#c084fc',
      borderPrimary: '#7c3aed',
      borderSecondary: '#9333ea',
      accent: '#a855f7',
      accentHover: '#9333ea',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#c084fc',
      cardBg: '#581c87',
      cardBorder: '#7c3aed',
      cardShadow: 'rgba(168, 85, 247, 0.3)',
    },
  },
  
  // PRIMARY COLOR VARIATIONS - ORANGES
  apricot: {
    id: 'apricot',
    name: 'Apricot',
    description: 'Soft apricot orange',
    colors: {
      bgPrimary: '#fff5eb',
      bgSecondary: '#ffe5d6',
      bgTertiary: '#ffd5c2',
      bgHover: '#ffc5ad',
      textPrimary: '#663d26',
      textSecondary: '#804d33',
      textTertiary: '#995c40',
      borderPrimary: '#ffb380',
      borderSecondary: '#ffa366',
      accent: '#ff8c69',
      accentHover: '#ff7350',
      accentText: '#ffffff',
      success: '#ffa07a',
      error: '#cd5c5c',
      warning: '#ff8c69',
      info: '#f4a460',
      cardBg: '#fffaf5',
      cardBorder: '#ffd5c2',
      cardShadow: 'rgba(255, 140, 105, 0.2)',
    },
  },

  midnight_blue: {
    id: 'midnight_blue',
    name: 'Midnight Blue',
    description: 'Deep night blue',
    colors: {
      bgPrimary: '#0d1a33',
      bgSecondary: '#1a2d52',
      bgTertiary: '#264070',
      bgHover: '#33538f',
      textPrimary: '#ccd9f2',
      textSecondary: '#b3c7e6',
      textTertiary: '#99b5da',
      borderPrimary: '#4d7acc',
      borderSecondary: '#3366b8',
      accent: '#1e3a8a',
      accentHover: '#172e6e',
      accentText: '#ffffff',
      success: '#4169e1',
      error: '#ff6b6b',
      warning: '#4d7acc',
      info: '#1e3a8a',
      cardBg: '#1a2d52',
      cardBorder: '#4d7acc',
      cardShadow: 'rgba(30, 58, 138, 0.4)',
    },
  },

  aqua: {
    id: 'aqua',
    name: 'Aqua Dream',
    description: 'Bright turquoise and teal',
    colors: {
      bgPrimary: '#e6ffff',
      bgSecondary: '#b3f5ff',
      bgTertiary: '#80ebff',
      bgHover: '#4de0ff',
      
      textPrimary: '#003d47',
      textSecondary: '#00667a',
      textTertiary: '#008fad',
      
      borderPrimary: '#1ac9e6',
      borderSecondary: '#00b8d9',
      
      accent: '#00d9ff',
      accentHover: '#00bfff',
      accentText: '#003344',
      
      success: '#00ff99',
      error: '#ff3366',
      warning: '#ffbb00',
      info: '#0099ff',
      
      cardBg: '#ffffff',
      cardBorder: '#66e0ff',
      cardShadow: 'rgba(0, 217, 255, 0.3)',
    },
  },
  arctic: {
    id: 'arctic',
    name: 'Arctic Ice',
    description: 'Frozen cyan blue',
    colors: {
      bgPrimary: '#ecfeff',
      bgSecondary: '#cffafe',
      bgTertiary: '#a5f3fc',
      bgHover: '#cffafe',
      textPrimary: '#164e63',
      textSecondary: '#155e75',
      textTertiary: '#0e7490',
      borderPrimary: '#67e8f9',
      borderSecondary: '#22d3ee',
      accent: '#06b6d4',
      accentHover: '#0891b2',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#06b6d4',
      cardBg: '#ffffff',
      cardBorder: '#67e8f9',
      cardShadow: 'rgba(6, 182, 212, 0.2)',
    },
  },
  
  ash: {
    id: 'ash',
    name: 'Volcanic Ash',
    description: 'Dusty ash gray',
    colors: {
      bgPrimary: '#e8e8eb',
      bgSecondary: '#d4d4da',
      bgTertiary: '#c0c0c9',
      bgHover: '#acacb8',
      textPrimary: '#26262d',
      textSecondary: '#393947',
      textTertiary: '#4d4d5c',
      borderPrimary: '#8a8a99',
      borderSecondary: '#707080',
      accent: '#696969',
      accentHover: '#555555',
      accentText: '#ffffff',
      success: '#a9a9a9',
      error: '#696969',
      warning: '#808080',
      info: '#778899',
      cardBg: '#f5f5f8',
      cardBorder: '#c0c0c9',
      cardShadow: 'rgba(105, 105, 105, 0.2)',
    },
  },

  aurora: {
    id: 'aurora',
    name: 'Aurora',
    description: 'Northern lights inspired',
    colors: {
      bgPrimary: '#022c22',
      bgSecondary: '#064e3b',
      bgTertiary: '#065f46',
      bgHover: '#064e3b',
      textPrimary: '#a7f3d0',
      textSecondary: '#6ee7b7',
      textTertiary: '#34d399',
      borderPrimary: '#047857',
      borderSecondary: '#059669',
      accent: '#10b981',
      accentHover: '#059669',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#06b6d4',
      cardBg: '#064e3b',
      cardBorder: '#047857',
      cardShadow: 'rgba(16, 185, 129, 0.3)',
    },
  },

  // 50 New Unique Themes with Truly Diverse Semantic Colors
  
  bamboo: {
    id: 'bamboo',
    name: 'Bamboo Forest',
    description: 'Natural bamboo greens',
    colors: {
      bgPrimary: '#f5f9f0',
      bgSecondary: '#e8f2dc',
      bgTertiary: '#dbebc8',
      bgHover: '#cee4b4',
      textPrimary: '#2d4a1e',
      textSecondary: '#3f6329',
      textTertiary: '#527c34',
      borderPrimary: '#8fb573',
      borderSecondary: '#7a9e5f',
      accent: '#6b8e23',
      accentHover: '#556b1e',
      accentText: '#ffffff',
      success: '#7cb342',
      error: '#e53935',
      warning: '#fb8c00',
      info: '#039be5',
      cardBg: '#fcfef9',
      cardBorder: '#dbebc8',
      cardShadow: 'rgba(107, 142, 35, 0.15)',
    },
  },

  basalt: {
    id: 'basalt',
    name: 'Basalt',
    description: 'Volcanic rock gray',
    colors: {
      bgPrimary: '#2b2b2b',
      bgSecondary: '#3a3a3a',
      bgTertiary: '#494949',
      bgHover: '#585858',
      textPrimary: '#e8e8e8',
      textSecondary: '#d0d0d0',
      textTertiary: '#b8b8b8',
      borderPrimary: '#707070',
      borderSecondary: '#606060',
      accent: '#708090',
      accentHover: '#556b7a',
      accentText: '#ffffff',
      success: '#90ee90',
      error: '#cd5c5c',
      warning: '#daa520',
      info: '#87ceeb',
      cardBg: '#3a3a3a',
      cardBorder: '#707070',
      cardShadow: 'rgba(112, 128, 144, 0.3)',
    },
  },

  berry: {
    id: 'berry',
    name: 'Berry Blast',
    description: 'Mixed berry colors',
    colors: {
      bgPrimary: '#fdf2f8',
      bgSecondary: '#fce7f3',
      bgTertiary: '#fbcfe8',
      bgHover: '#fce7f3',
      textPrimary: '#701a75',
      textSecondary: '#86198f',
      textTertiary: '#a21caf',
      borderPrimary: '#f0abfc',
      borderSecondary: '#e879f9',
      accent: '#d946ef',
      accentHover: '#c026d3',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#f43f5e',
      warning: '#f59e0b',
      info: '#d946ef',
      cardBg: '#ffffff',
      cardBorder: '#f0abfc',
      cardShadow: 'rgba(217, 70, 239, 0.25)',
    },
  },
  
  // PRIMARY COLOR VARIATIONS - BLUES
  blueberry: {
    id: 'blueberry',
    name: 'Blueberry',
    description: 'Sweet blueberry blue',
    colors: {
      bgPrimary: '#e6e6f5',
      bgSecondary: '#cccceb',
      bgTertiary: '#b3b3e0',
      bgHover: '#9999d6',
      textPrimary: '#1a1a4d',
      textSecondary: '#2d2d66',
      textTertiary: '#404080',
      borderPrimary: '#6666b3',
      borderSecondary: '#4d4d9e',
      accent: '#4169e1',
      accentHover: '#3355c7',
      accentText: '#ffffff',
      success: '#6495ed',
      error: '#dc143c',
      warning: '#dda0dd',
      info: '#4169e1',
      cardBg: '#f5f5fa',
      cardBorder: '#b3b3e0',
      cardShadow: 'rgba(65, 105, 225, 0.2)',
    },
  },

  blush: {
    id: 'blush',
    name: 'Blush',
    description: 'Soft blush pink',
    colors: {
      bgPrimary: '#fdf2f8',
      bgSecondary: '#fce7f3',
      bgTertiary: '#fbcfe8',
      bgHover: '#fce7f3',
      textPrimary: '#831843',
      textSecondary: '#9d174d',
      textTertiary: '#be185d',
      borderPrimary: '#f9a8d4',
      borderSecondary: '#f472b6',
      accent: '#ec4899',
      accentHover: '#db2777',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#ec4899',
      cardBg: '#ffffff',
      cardBorder: '#f9a8d4',
      cardShadow: 'rgba(236, 72, 153, 0.2)',
    },
  },
  
  bronze: {
    id: 'bronze',
    name: 'Bronze Age',
    description: 'Metallic bronze',
    colors: {
      bgPrimary: '#f5e8d8',
      bgSecondary: '#e8d4b8',
      bgTertiary: '#dbc098',
      bgHover: '#ceac78',
      textPrimary: '#3d2817',
      textSecondary: '#5c3d24',
      textTertiary: '#7a5436',
      borderPrimary: '#b8935f',
      borderSecondary: '#a67c52',
      accent: '#cd7f32',
      accentHover: '#b36b28',
      accentText: '#ffffff',
      success: '#cd853f',
      error: '#a0522d',
      warning: '#daa520',
      info: '#cd7f32',
      cardBg: '#faf5ed',
      cardBorder: '#dbc098',
      cardShadow: 'rgba(205, 127, 50, 0.2)',
    },
  },

  bubblegum: {
    id: 'bubblegum',
    name: 'Bubblegum',
    description: 'Sweet pink and blue',
    colors: {
      bgPrimary: '#fef3ff',
      bgSecondary: '#fae8ff',
      bgTertiary: '#f5d0fe',
      bgHover: '#f0b8fd',
      
      textPrimary: '#4a0844',
      textSecondary: '#701a75',
      textTertiary: '#a21caf',
      
      borderPrimary: '#e9a0fc',
      borderSecondary: '#e078fa',
      
      accent: '#d946ef',
      accentHover: '#c026d3',
      accentText: '#ffffff',
      
      success: '#22d3ee',
      error: '#f43f5e',
      warning: '#fbbf24',
      info: '#a78bfa',
      
      cardBg: '#ffffff',
      cardBorder: '#f0c0fe',
      cardShadow: 'rgba(217, 70, 239, 0.15)',
    },
  },
  candy: {
    id: 'candy',
    name: 'Candy Pop',
    description: 'Sweet pastel colors',
    colors: {
      bgPrimary: '#fff0f8',
      bgSecondary: '#fce4f4',
      bgTertiary: '#f8d4f0',
      bgHover: '#f4c4ec',
      
      textPrimary: '#4a1555',
      textSecondary: '#7a2580',
      textTertiary: '#a035aa',
      
      borderPrimary: '#f0a4e8',
      borderSecondary: '#e874e0',
      
      accent: '#d946ef',
      accentHover: '#c026d3',
      accentText: '#ffffff',
      
      success: '#10d97f',
      error: '#f43f5e',
      warning: '#fbbf24',
      info: '#8b5cf6',
      
      cardBg: '#ffffff',
      cardBorder: '#f8c8f0',
      cardShadow: 'rgba(217, 70, 239, 0.15)',
    },
  },
  caramel: {
    id: 'caramel',
    name: 'Caramel',
    description: 'Sweet caramel brown',
    colors: {
      bgPrimary: '#f5ebe0',
      bgSecondary: '#e8d4c0',
      bgTertiary: '#dbbda0',
      bgHover: '#cea680',
      textPrimary: '#3d2817',
      textSecondary: '#5c3d24',
      textTertiary: '#7a5436',
      borderPrimary: '#b8935f',
      borderSecondary: '#a67c52',
      accent: '#c68642',
      accentHover: '#a86f35',
      accentText: '#ffffff',
      success: '#daa520',
      error: '#a0522d',
      warning: '#f4a460',
      info: '#cd853f',
      cardBg: '#faf5ed',
      cardBorder: '#dbbda0',
      cardShadow: 'rgba(198, 134, 66, 0.2)',
    },
  },

  champagne: {
    id: 'champagne',
    name: 'Champagne',
    description: 'Elegant champagne gold',
    colors: {
      bgPrimary: '#faf8f0',
      bgSecondary: '#f5f0e0',
      bgTertiary: '#f0e8d0',
      bgHover: '#ebe0c0',
      textPrimary: '#4d4433',
      textSecondary: '#665947',
      textTertiary: '#806e5c',
      borderPrimary: '#d9cc99',
      borderSecondary: '#ccbf80',
      accent: '#f7e7ce',
      accentHover: '#e6d4b5',
      accentText: '#4d4433',
      success: '#f0e68c',
      error: '#cd853f',
      warning: '#daa520',
      info: '#bdb76b',
      cardBg: '#fffdf5',
      cardBorder: '#f0e8d0',
      cardShadow: 'rgba(247, 231, 206, 0.3)',
    },
  },

  charcoal: {
    id: 'charcoal',
    name: 'Charcoal',
    description: 'Deep charcoal black',
    colors: {
      bgPrimary: '#1a1a1a',
      bgSecondary: '#2d2d2d',
      bgTertiary: '#404040',
      bgHover: '#535353',
      textPrimary: '#e0e0e0',
      textSecondary: '#c0c0c0',
      textTertiary: '#a0a0a0',
      borderPrimary: '#666666',
      borderSecondary: '#4d4d4d',
      accent: '#808080',
      accentHover: '#666666',
      accentText: '#ffffff',
      success: '#90ee90',
      error: '#f08080',
      warning: '#ffd700',
      info: '#87ceeb',
      cardBg: '#2d2d2d',
      cardBorder: '#666666',
      cardShadow: 'rgba(128, 128, 128, 0.3)',
    },
  },

  cherry: {
    id: 'cherry',
    name: 'Cherry Blossom',
    description: 'Soft cherry pink',
    colors: {
      bgPrimary: '#fdf2f8',
      bgSecondary: '#fce7f3',
      bgTertiary: '#fbcfe8',
      bgHover: '#fce7f3',
      textPrimary: '#831843',
      textSecondary: '#9d174d',
      textTertiary: '#be185d',
      borderPrimary: '#f9a8d4',
      borderSecondary: '#f472b6',
      accent: '#ec4899',
      accentHover: '#db2777',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#ec4899',
      cardBg: '#ffffff',
      cardBorder: '#f9a8d4',
      cardShadow: 'rgba(236, 72, 153, 0.2)',
    },
  },
  
  chocolate: {
    id: 'chocolate',
    name: 'Chocolate',
    description: 'Rich chocolate brown',
    colors: {
      bgPrimary: '#44403c',
      bgSecondary: '#57534e',
      bgTertiary: '#78716c',
      bgHover: '#57534e',
      textPrimary: '#fafaf9',
      textSecondary: '#e7e5e4',
      textTertiary: '#d6d3d1',
      borderPrimary: '#78716c',
      borderSecondary: '#a8a29e',
      accent: '#d97706',
      accentHover: '#b45309',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#3b82f6',
      cardBg: '#57534e',
      cardBorder: '#78716c',
      cardShadow: 'rgba(217, 119, 6, 0.2)',
    },
  },
  
  // UNIQUE COMBINATIONS
  citrus: {
    id: 'citrus',
    name: 'Citrus Burst',
    description: 'Bright lime and yellow',
    colors: {
      bgPrimary: '#ffffe6',
      bgSecondary: '#ffffb3',
      bgTertiary: '#ffff80',
      bgHover: '#ffff4d',
      
      textPrimary: '#4d4000',
      textSecondary: '#665500',
      textTertiary: '#806a00',
      
      borderPrimary: '#ffdd00',
      borderSecondary: '#ffcc00',
      
      accent: '#dfff00',
      accentHover: '#ccff00',
      accentText: '#333300',
      
      success: '#88ff00',
      error: '#ff6600',
      warning: '#ffaa00',
      info: '#00ccff',
      
      cardBg: '#ffffff',
      cardBorder: '#ffff66',
      cardShadow: 'rgba(223, 255, 0, 0.3)',
    },
  },
  cobalt: {
    id: 'cobalt',
    name: 'Cobalt Blue',
    description: 'Deep rich blue',
    colors: {
      bgPrimary: '#001a33',
      bgSecondary: '#002d52',
      bgTertiary: '#004080',
      bgHover: '#0053a6',
      textPrimary: '#cce0f2',
      textSecondary: '#b3d1e6',
      textTertiary: '#99c2da',
      borderPrimary: '#4d94cc',
      borderSecondary: '#3380b8',
      accent: '#0066cc',
      accentHover: '#0052a3',
      accentText: '#ffffff',
      success: '#3380b8',
      error: '#ff6b6b',
      warning: '#4d94cc',
      info: '#0066cc',
      cardBg: '#002d52',
      cardBorder: '#4d94cc',
      cardShadow: 'rgba(0, 102, 204, 0.4)',
    },
  },

  copper: {
    id: 'copper',
    name: 'Copper',
    description: 'Metallic copper shine',
    colors: {
      bgPrimary: '#f5e8e0',
      bgSecondary: '#e8d4c0',
      bgTertiary: '#dbc0a0',
      bgHover: '#ceac80',
      textPrimary: '#3d2817',
      textSecondary: '#5c3d24',
      textTertiary: '#7a5436',
      borderPrimary: '#b8935f',
      borderSecondary: '#a67c52',
      accent: '#b87333',
      accentHover: '#9a5f2a',
      accentText: '#ffffff',
      success: '#cd853f',
      error: '#8b4513',
      warning: '#d2691e',
      info: '#b87333',
      cardBg: '#faf5ed',
      cardBorder: '#dbc0a0',
      cardShadow: 'rgba(184, 115, 51, 0.2)',
    },
  },

  coral: {
    id: 'coral',
    name: 'Coral Reef',
    description: 'Bright coral and pink',
    colors: {
      bgPrimary: '#fff0f5',
      bgSecondary: '#ffd6e7',
      bgTertiary: '#ffb3d9',
      bgHover: '#ff99cc',
      
      textPrimary: '#6b0028',
      textSecondary: '#9b0039',
      textTertiary: '#cb004b',
      
      borderPrimary: '#ff80bf',
      borderSecondary: '#ff4da6',
      
      accent: '#ff1a8c',
      accentHover: '#e60073',
      accentText: '#ffffff',
      
      success: '#00ff88',
      error: '#ff0055',
      warning: '#ffaa00',
      info: '#0099ff',
      
      cardBg: '#ffffff',
      cardBorder: '#ffb3e6',
      cardShadow: 'rgba(255, 26, 140, 0.25)',
    },
  },
  cosmic: {
    id: 'cosmic',
    name: 'Cosmic Dust',
    description: 'Deep space purple',
    colors: {
      bgPrimary: '#0d0221',
      bgSecondary: '#1a0440',
      bgTertiary: '#270659',
      bgHover: '#340872',
      textPrimary: '#e0c3fc',
      textSecondary: '#c89ff5',
      textTertiary: '#b07bee',
      borderPrimary: '#8a57e7',
      borderSecondary: '#7233e0',
      accent: '#5a0fd9',
      accentHover: '#4a0cb3',
      accentText: '#ffffff',
      success: '#da70d6',
      error: '#dc2626',
      warning: '#7c3aed',
      info: '#a855f7',
      cardBg: '#1a0440',
      cardBorder: '#8a57e7',
      cardShadow: 'rgba(90, 15, 217, 0.4)',
    },
  },

  cranberry: {
    id: 'cranberry',
    name: 'Cranberry',
    description: 'Rich cranberry red',
    colors: {
      bgPrimary: '#f0e6eb',
      bgSecondary: '#e0ccd6',
      bgTertiary: '#d0b3c2',
      bgHover: '#c099ad',
      textPrimary: '#4d1a26',
      textSecondary: '#662d39',
      textTertiary: '#80404d',
      borderPrimary: '#b36680',
      borderSecondary: '#9e4d6b',
      accent: '#9e0142',
      accentHover: '#7a0133',
      accentText: '#ffffff',
      success: '#dc143c',
      error: '#8b0000',
      warning: '#ff1493',
      info: '#9e0142',
      cardBg: '#f8f5f7',
      cardBorder: '#d0b3c2',
      cardShadow: 'rgba(158, 1, 66, 0.2)',
    },
  },

  cream: {
    id: 'cream',
    name: 'Cream',
    description: 'Soft cream white',
    colors: {
      bgPrimary: '#fffef5',
      bgSecondary: '#fffceb',
      bgTertiary: '#fffae0',
      bgHover: '#fff8d6',
      textPrimary: '#665533',
      textSecondary: '#806a47',
      textTertiary: '#99805c',
      borderPrimary: '#e6d9b3',
      borderSecondary: '#d9cc99',
      accent: '#d4a574',
      accentHover: '#b88a5f',
      accentText: '#ffffff',
      success: '#f0e68c',
      error: '#cd853f',
      warning: '#daa520',
      info: '#d4a574',
      cardBg: '#ffffff',
      cardBorder: '#fffae0',
      cardShadow: 'rgba(212, 165, 116, 0.15)',
    },
  },

  crimson: {
    id: 'crimson',
    name: 'Crimson',
    description: 'Bold red and burgundy',
    colors: {
      bgPrimary: '#fef2f2',
      bgSecondary: '#fee2e2',
      bgTertiary: '#fecaca',
      bgHover: '#fef2f2',
      textPrimary: '#7f1d1d',
      textSecondary: '#991b1b',
      textTertiary: '#b91c1c',
      borderPrimary: '#fca5a5',
      borderSecondary: '#f87171',
      accent: '#dc2626',
      accentHover: '#b91c1c',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#dc2626',
      warning: '#f59e0b',
      info: '#3b82f6',
      cardBg: '#ffffff',
      cardBorder: '#fca5a5',
      cardShadow: 'rgba(220, 38, 38, 0.2)',
    },
  },
  
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Neon future vibes',
    colors: {
      bgPrimary: '#0a0e27',
      bgSecondary: '#16213e',
      bgTertiary: '#1a1f3a',
      bgHover: '#1a1f3a',
      
      textPrimary: '#00fff9',
      textSecondary: '#0ef3f7',
      textTertiary: '#0db3b8',
      
      borderPrimary: '#1a1f3a',
      borderSecondary: '#ff00ff',
      
      accent: '#ff00ff',
      accentHover: '#cc00cc',
      accentText: '#0a0e27',
      
      success: '#00ff41',
      error: '#ff0055',
      warning: '#ffea00',
      info: '#00fff9',
      
      cardBg: '#16213e',
      cardBorder: '#ff00ff',
      cardShadow: 'rgba(255, 0, 255, 0.2)',
    },
  },
  dark: {
    id: 'dark',
    name: 'Dark',
    description: 'Easy on the eyes',
    colors: {
      bgPrimary: '#0f172a',
      bgSecondary: '#1e293b',
      bgTertiary: '#334155',
      bgHover: '#334155',
      
      textPrimary: '#f1f5f9',
      textSecondary: '#cbd5e1',
      textTertiary: '#94a3b8',
      
      borderPrimary: '#334155',
      borderSecondary: '#475569',
      
      accent: '#3b82f6',
      accentHover: '#2563eb',
      accentText: '#ffffff',
      
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#3b82f6',
      
      cardBg: '#1e293b',
      cardBorder: '#334155',
      cardShadow: 'rgba(0, 0, 0, 0.3)',
    },
  },
  deepSea: {
    id: 'deepSea',
    name: 'Deep Sea',
    description: 'Dark ocean teal',
    colors: {
      bgPrimary: '#134e4a',
      bgSecondary: '#115e59',
      bgTertiary: '#0f766e',
      bgHover: '#115e59',
      textPrimary: '#99f6e4',
      textSecondary: '#5eead4',
      textTertiary: '#2dd4bf',
      borderPrimary: '#0f766e',
      borderSecondary: '#0d9488',
      accent: '#14b8a6',
      accentHover: '#0d9488',
      accentText: '#ffffff',
      success: '#14b8a6',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#2dd4bf',
      cardBg: '#115e59',
      cardBorder: '#0f766e',
      cardShadow: 'rgba(20, 184, 166, 0.3)',
    },
  },
  
  // NEUTRALS AND EARTH TONES
  desert: {
    id: 'desert',
    name: 'Desert Mirage',
    description: 'Warm sandy tones',
    colors: {
      bgPrimary: '#f4e8d8',
      bgSecondary: '#e8d4b8',
      bgTertiary: '#d4b896',
      bgHover: '#c9a876',
      textPrimary: '#3d2817',
      textSecondary: '#5c3d24',
      textTertiary: '#7a5436',
      borderPrimary: '#b89968',
      borderSecondary: '#a67c52',
      accent: '#d2691e',
      accentHover: '#b8560f',
      accentText: '#ffffff',
      success: '#cd853f',
      error: '#cd5c5c',
      warning: '#ff8c00',
      info: '#4682b4',
      cardBg: '#faf5ed',
      cardBorder: '#d4b896',
      cardShadow: 'rgba(210, 105, 30, 0.2)',
    },
  },

  dracula: {
    id: 'dracula',
    name: 'Dracula',
    description: 'Classic vampire theme',
    colors: {
      bgPrimary: '#282a36',
      bgSecondary: '#383a59',
      bgTertiary: '#44475a',
      bgHover: '#44475a',
      
      textPrimary: '#f8f8f2',
      textSecondary: '#f8f8f2',
      textTertiary: '#6272a4',
      
      borderPrimary: '#44475a',
      borderSecondary: '#6272a4',
      
      accent: '#bd93f9',
      accentHover: '#9580e0',
      accentText: '#282a36',
      
      success: '#50fa7b',
      error: '#ff5555',
      warning: '#f1fa8c',
      info: '#8be9fd',
      
      cardBg: '#383a59',
      cardBorder: '#44475a',
      cardShadow: 'rgba(189, 147, 249, 0.1)',
    },
  },
  dusk: {
    id: 'dusk',
    name: 'Dusk',
    description: 'Evening twilight',
    colors: {
      bgPrimary: '#2c1a3d',
      bgSecondary: '#3d2652',
      bgTertiary: '#4e3267',
      bgHover: '#5f3e7c',
      textPrimary: '#e8d5f2',
      textSecondary: '#d4bfe6',
      textTertiary: '#c0a9da',
      borderPrimary: '#8a6ba8',
      borderSecondary: '#75579c',
      accent: '#9b59b6',
      accentHover: '#8e44ad',
      accentText: '#ffffff',
      success: '#9b59b6',
      error: '#e74c3c',
      warning: '#f39c12',
      info: '#8e44ad',
      cardBg: '#3d2652',
      cardBorder: '#8a6ba8',
      cardShadow: 'rgba(155, 89, 182, 0.3)',
    },
  },

  electric: {
    id: 'electric',
    name: 'Electric Blue',
    description: 'Bright electric energy',
    colors: {
      bgPrimary: '#0a0a1a',
      bgSecondary: '#1a1a2d',
      bgTertiary: '#2d2d40',
      bgHover: '#404053',
      textPrimary: '#d0e0ff',
      textSecondary: '#b3d1ff',
      textTertiary: '#99c2ff',
      borderPrimary: '#4d94ff',
      borderSecondary: '#3380ff',
      accent: '#00bfff',
      accentHover: '#0099cc',
      accentText: '#ffffff',
      success: '#00bfff',
      error: '#ff1493',
      warning: '#00ffff',
      info: '#1e90ff',
      cardBg: '#1a1a2d',
      cardBorder: '#4d94ff',
      cardShadow: 'rgba(0, 191, 255, 0.4)',
    },
  },

  emerald: {
    id: 'emerald',
    name: 'Emerald',
    description: 'Rich jewel green',
    colors: {
      bgPrimary: '#ecfdf5',
      bgSecondary: '#d1fae5',
      bgTertiary: '#a7f3d0',
      bgHover: '#d1fae5',
      textPrimary: '#064e3b',
      textSecondary: '#065f46',
      textTertiary: '#047857',
      borderPrimary: '#6ee7b7',
      borderSecondary: '#34d399',
      accent: '#10b981',
      accentHover: '#059669',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#06b6d4',
      cardBg: '#ffffff',
      cardBorder: '#6ee7b7',
      cardShadow: 'rgba(16, 185, 129, 0.25)',
    },
  },
  
  espresso: {
    id: 'espresso',
    name: 'Espresso',
    description: 'Dark rich coffee',
    colors: {
      bgPrimary: '#1c1410',
      bgSecondary: '#2c1f18',
      bgTertiary: '#3d2b20',
      bgHover: '#4a3528',
      textPrimary: '#f5deb3',
      textSecondary: '#d4b896',
      textTertiary: '#b89968',
      borderPrimary: '#6b5444',
      borderSecondary: '#8b6f47',
      accent: '#d2691e',
      accentHover: '#b8591a',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ff6b6b',
      warning: '#ffa500',
      info: '#87ceeb',
      cardBg: '#241c16',
      cardBorder: '#6b5444',
      cardShadow: 'rgba(210, 105, 30, 0.2)',
    },
  },
  
  flamingo: {
    id: 'flamingo',
    name: 'Flamingo',
    description: 'Soft pink elegance',
    colors: {
      bgPrimary: '#fff0f5',
      bgSecondary: '#ffe0eb',
      bgTertiary: '#ffd0e1',
      bgHover: '#ffc0d7',
      textPrimary: '#661a33',
      textSecondary: '#802d47',
      textTertiary: '#99405c',
      borderPrimary: '#ff99bb',
      borderSecondary: '#ff80a8',
      accent: '#ff69b4',
      accentHover: '#ff1493',
      accentText: '#ffffff',
      success: '#ff69b4',
      error: '#dc143c',
      warning: '#ff1493',
      info: '#ff80a8',
      cardBg: '#fffafc',
      cardBorder: '#ffd0e1',
      cardShadow: 'rgba(255, 105, 180, 0.2)',
    },
  },

  fog: {
    id: 'fog',
    name: 'Morning Fog',
    description: 'Misty gray morning',
    colors: {
      bgPrimary: '#f0f0f2',
      bgSecondary: '#e0e0e6',
      bgTertiary: '#d0d0da',
      bgHover: '#c0c0ce',
      textPrimary: '#333340',
      textSecondary: '#474759',
      textTertiary: '#5c5c73',
      borderPrimary: '#9393a8',
      borderSecondary: '#7a7a8f',
      accent: '#708090',
      accentHover: '#556b7a',
      accentText: '#ffffff',
      success: '#b0c4de',
      error: '#bc8f8f',
      warning: '#d3d3d3',
      info: '#778899',
      cardBg: '#f8f8fa',
      cardBorder: '#d0d0da',
      cardShadow: 'rgba(112, 128, 144, 0.15)',
    },
  },

  forest: {
    id: 'forest',
    name: 'Forest',
    description: 'Natural green tones',
    colors: {
      bgPrimary: '#0a1f0a',
      bgSecondary: '#14532d',
      bgTertiary: '#166534',
      bgHover: '#166534',
      
      textPrimary: '#f0fdf4',
      textSecondary: '#dcfce7',
      textTertiary: '#bbf7d0',
      
      borderPrimary: '#166534',
      borderSecondary: '#22c55e',
      
      accent: '#22c55e',
      accentHover: '#16a34a',
      accentText: '#ffffff',
      
      success: '#22c55e',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#3b82f6',
      
      cardBg: '#14532d',
      cardBorder: '#166534',
      cardShadow: 'rgba(34, 197, 94, 0.1)',
    },
  },
  forestGreen: {
    id: 'forestGreen',
    name: 'Forest Green',
    description: 'Deep forest green',
    colors: {
      bgPrimary: '#f0fdf4',
      bgSecondary: '#dcfce7',
      bgTertiary: '#bbf7d0',
      bgHover: '#dcfce7',
      textPrimary: '#14532d',
      textSecondary: '#166534',
      textTertiary: '#15803d',
      borderPrimary: '#86efac',
      borderSecondary: '#4ade80',
      accent: '#22c55e',
      accentHover: '#16a34a',
      accentText: '#ffffff',
      success: '#22c55e',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#3b82f6',
      cardBg: '#ffffff',
      cardBorder: '#86efac',
      cardShadow: 'rgba(34, 197, 94, 0.2)',
    },
  },
  
  fuchsia: {
    id: 'fuchsia',
    name: 'Fuchsia Pop',
    description: 'Vibrant magenta fuchsia',
    colors: {
      bgPrimary: '#fdf4ff',
      bgSecondary: '#fae8ff',
      bgTertiary: '#f5d0fe',
      bgHover: '#fae8ff',
      textPrimary: '#701a75',
      textSecondary: '#86198f',
      textTertiary: '#a21caf',
      borderPrimary: '#e879f9',
      borderSecondary: '#d946ef',
      accent: '#c026d3',
      accentHover: '#a21caf',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#c026d3',
      cardBg: '#ffffff',
      cardBorder: '#e879f9',
      cardShadow: 'rgba(192, 38, 211, 0.25)',
    },
  },
  
  glacier: {
    id: 'glacier',
    name: 'Glacier',
    description: 'Icy blue whites',
    colors: {
      bgPrimary: '#e8f4f8',
      bgSecondary: '#d4e9f0',
      bgTertiary: '#c0dde8',
      bgHover: '#acd2e0',
      textPrimary: '#0a3d62',
      textSecondary: '#1e5f7e',
      textTertiary: '#2e7d9a',
      borderPrimary: '#82c4d8',
      borderSecondary: '#6ab3cc',
      accent: '#00a8cc',
      accentHover: '#0086a8',
      accentText: '#ffffff',
      success: '#87ceeb',
      error: '#e74c3c',
      warning: '#3dc2ec',
      info: '#00a8cc',
      cardBg: '#f5fbfd',
      cardBorder: '#c0dde8',
      cardShadow: 'rgba(0, 168, 204, 0.15)',
    },
  },

  golden: {
    id: 'golden',
    name: 'Golden Hour',
    description: 'Warm golden sunset',
    colors: {
      bgPrimary: '#fffcf5',
      bgSecondary: '#fff8e1',
      bgTertiary: '#ffecb3',
      bgHover: '#fff8e1',
      textPrimary: '#6b4e1f',
      textSecondary: '#8d6e2e',
      textTertiary: '#b8941f',
      borderPrimary: '#ffd54f',
      borderSecondary: '#ffca28',
      accent: '#ffc107',
      accentHover: '#ffb300',
      accentText: '#000000',
      success: '#10b981',
      error: '#ef4444',
      warning: '#ffc107',
      info: '#3b82f6',
      cardBg: '#ffffff',
      cardBorder: '#ffd54f',
      cardShadow: 'rgba(255, 193, 7, 0.25)',
    },
  },
  
  graphite: {
    id: 'graphite',
    name: 'Graphite',
    description: 'Dark graphite gray',
    colors: {
      bgPrimary: '#18181b',
      bgSecondary: '#27272a',
      bgTertiary: '#3f3f46',
      bgHover: '#27272a',
      textPrimary: '#fafafa',
      textSecondary: '#e4e4e7',
      textTertiary: '#d4d4d8',
      borderPrimary: '#52525b',
      borderSecondary: '#71717a',
      accent: '#a1a1aa',
      accentHover: '#71717a',
      accentText: '#18181b',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#3b82f6',
      cardBg: '#27272a',
      cardBorder: '#3f3f46',
      cardShadow: 'rgba(161, 161, 170, 0.2)',
    },
  },
  
  gruvbox: {
    id: 'gruvbox',
    name: 'Gruvbox',
    description: 'Retro warm colors',
    colors: {
      bgPrimary: '#282828',
      bgSecondary: '#3c3836',
      bgTertiary: '#504945',
      bgHover: '#504945',
      
      textPrimary: '#ebdbb2',
      textSecondary: '#d5c4a1',
      textTertiary: '#bdae93',
      
      borderPrimary: '#504945',
      borderSecondary: '#665c54',
      
      accent: '#fe8019',
      accentHover: '#d65d0e',
      accentText: '#282828',
      
      success: '#b8bb26',
      error: '#fb4934',
      warning: '#fabd2f',
      info: '#83a598',
      
      cardBg: '#3c3836',
      cardBorder: '#504945',
      cardShadow: 'rgba(254, 128, 25, 0.1)',
    },
  },
  hazelnut: {
    id: 'hazelnut',
    name: 'Hazelnut',
    description: 'Warm hazelnut brown',
    colors: {
      bgPrimary: '#f5f0e8',
      bgSecondary: '#e8e0d4',
      bgTertiary: '#dbd0c0',
      bgHover: '#cec0ac',
      textPrimary: '#3d3328',
      textSecondary: '#5c473d',
      textTertiary: '#7a5c52',
      borderPrimary: '#b89373',
      borderSecondary: '#a67c5f',
      accent: '#8b7355',
      accentHover: '#705c44',
      accentText: '#ffffff',
      success: '#d2b48c',
      error: '#a0522d',
      warning: '#daa520',
      info: '#8b7355',
      cardBg: '#faf8f5',
      cardBorder: '#dbd0c0',
      cardShadow: 'rgba(139, 115, 85, 0.2)',
    },
  },

  highContrast: {
    id: 'highContrast',
    name: 'High Contrast',
    description: 'Maximum readability',
    colors: {
      bgPrimary: '#000000',
      bgSecondary: '#1a1a1a',
      bgTertiary: '#2d2d2d',
      bgHover: '#2d2d2d',
      
      textPrimary: '#ffffff',
      textSecondary: '#ffffff',
      textTertiary: '#cccccc',
      
      borderPrimary: '#ffffff',
      borderSecondary: '#ffffff',
      
      accent: '#00ff00',
      accentHover: '#00cc00',
      accentText: '#000000',
      
      success: '#00ff00',
      error: '#ff0000',
      warning: '#ffff00',
      info: '#00ffff',
      
      cardBg: '#1a1a1a',
      cardBorder: '#ffffff',
      cardShadow: 'rgba(255, 255, 255, 0.2)',
    },
  },
  honeycomb: {
    id: 'honeycomb',
    name: 'Honeycomb',
    description: 'Golden honey tones',
    colors: {
      bgPrimary: '#fff8e7',
      bgSecondary: '#ffefd5',
      bgTertiary: '#ffe6c3',
      bgHover: '#ffddb1',
      textPrimary: '#664400',
      textSecondary: '#805500',
      textTertiary: '#996600',
      borderPrimary: '#ffcc80',
      borderSecondary: '#ffb84d',
      accent: '#ffa500',
      accentHover: '#ff8c00',
      accentText: '#000000',
      success: '#ffa500',
      error: '#ff4500',
      warning: '#ffcc00',
      info: '#ff8c00',
      cardBg: '#fffcf5',
      cardBorder: '#ffe6c3',
      cardShadow: 'rgba(255, 165, 0, 0.2)',
    },
  },

  hotPink: {
    id: 'hotPink',
    name: 'Hot Pink',
    description: 'Vibrant hot pink',
    colors: {
      bgPrimary: '#fdf4ff',
      bgSecondary: '#fae8ff',
      bgTertiary: '#f5d0fe',
      bgHover: '#fae8ff',
      textPrimary: '#701a75',
      textSecondary: '#86198f',
      textTertiary: '#a21caf',
      borderPrimary: '#e879f9',
      borderSecondary: '#d946ef',
      accent: '#c026d3',
      accentHover: '#a21caf',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#c026d3',
      cardBg: '#ffffff',
      cardBorder: '#e879f9',
      cardShadow: 'rgba(192, 38, 211, 0.2)',
    },
  },
  
  // PRIMARY COLOR VARIATIONS - TEALS/CYANS
  indigo: {
    id: 'indigo',
    name: 'Indigo Night',
    description: 'Deep indigo blue',
    colors: {
      bgPrimary: '#eef2ff',
      bgSecondary: '#e0e7ff',
      bgTertiary: '#c7d2fe',
      bgHover: '#e0e7ff',
      textPrimary: '#312e81',
      textSecondary: '#3730a3',
      textTertiary: '#4338ca',
      borderPrimary: '#a5b4fc',
      borderSecondary: '#818cf8',
      accent: '#6366f1',
      accentHover: '#4f46e5',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#6366f1',
      cardBg: '#ffffff',
      cardBorder: '#a5b4fc',
      cardShadow: 'rgba(99, 102, 241, 0.25)',
    },
  },
  
  jade: {
    id: 'jade',
    name: 'Jade',
    description: 'Elegant jade green',
    colors: {
      bgPrimary: '#ecfdf5',
      bgSecondary: '#d1fae5',
      bgTertiary: '#a7f3d0',
      bgHover: '#d1fae5',
      textPrimary: '#064e3b',
      textSecondary: '#065f46',
      textTertiary: '#047857',
      borderPrimary: '#6ee7b7',
      borderSecondary: '#34d399',
      accent: '#10b981',
      accentHover: '#059669',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#06b6d4',
      cardBg: '#ffffff',
      cardBorder: '#6ee7b7',
      cardShadow: 'rgba(16, 185, 129, 0.2)',
    },
  },
  
  jungle: {
    id: 'jungle',
    name: 'Jungle',
    description: 'Dense jungle green',
    colors: {
      bgPrimary: '#0d1a0d',
      bgSecondary: '#1a2d1a',
      bgTertiary: '#264026',
      bgHover: '#335333',
      textPrimary: '#cce0cc',
      textSecondary: '#b3d1b3',
      textTertiary: '#99c299',
      borderPrimary: '#4d8a4d',
      borderSecondary: '#337033',
      accent: '#228b22',
      accentHover: '#1a6b1a',
      accentText: '#ffffff',
      success: '#228b22',
      error: '#8b0000',
      warning: '#9acd32',
      info: '#2e8b57',
      cardBg: '#1a2d1a',
      cardBorder: '#4d8a4d',
      cardShadow: 'rgba(34, 139, 34, 0.4)',
    },
  },

  kiwi: {
    id: 'kiwi',
    name: 'Kiwi',
    description: 'Fresh kiwi green',
    colors: {
      bgPrimary: '#f0f8e6',
      bgSecondary: '#e0f0cc',
      bgTertiary: '#d0e8b3',
      bgHover: '#c0e099',
      textPrimary: '#334d1a',
      textSecondary: '#47662d',
      textTertiary: '#5c8040',
      borderPrimary: '#93cc66',
      borderSecondary: '#7ab84d',
      accent: '#9acd32',
      accentHover: '#7fb028',
      accentText: '#000000',
      success: '#9acd32',
      error: '#cd5c5c',
      warning: '#f0e68c',
      info: '#7ab84d',
      cardBg: '#f8fcf0',
      cardBorder: '#d0e8b3',
      cardShadow: 'rgba(154, 205, 50, 0.2)',
    },
  },

  lagoon: {
    id: 'lagoon',
    name: 'Tropical Lagoon',
    description: 'Clear turquoise water',
    colors: {
      bgPrimary: '#e6f9f9',
      bgSecondary: '#ccf2f2',
      bgTertiary: '#b3ecec',
      bgHover: '#99e6e6',
      textPrimary: '#00404d',
      textSecondary: '#005966',
      textTertiary: '#007380',
      borderPrimary: '#66d9d9',
      borderSecondary: '#4dd2d2',
      accent: '#00ced1',
      accentHover: '#00b3b6',
      accentText: '#ffffff',
      success: '#00ced1',
      error: '#ff6b6b',
      warning: '#4dd2d2',
      info: '#00b3b6',
      cardBg: '#f5fcfc',
      cardBorder: '#b3ecec',
      cardShadow: 'rgba(0, 206, 209, 0.2)',
    },
  },

  lavender: {
    id: 'lavender',
    name: 'Lavender',
    description: 'Soft purple dreams',
    colors: {
      bgPrimary: '#1a1525',
      bgSecondary: '#2a1f3d',
      bgTertiary: '#3d2f54',
      bgHover: '#3d2f54',
      
      textPrimary: '#f3e8ff',
      textSecondary: '#e9d5ff',
      textTertiary: '#d8b4fe',
      
      borderPrimary: '#3d2f54',
      borderSecondary: '#8b5cf6',
      
      accent: '#a78bfa',
      accentHover: '#8b5cf6',
      accentText: '#ffffff',
      
      success: '#4ade80',
      error: '#f87171',
      warning: '#fbbf24',
      info: '#60a5fa',
      
      cardBg: '#2a1f3d',
      cardBorder: '#3d2f54',
      cardShadow: 'rgba(167, 139, 250, 0.1)',
    },
  },
  lemonade: {
    id: 'lemonade',
    name: 'Lemonade Stand',
    description: 'Bright citrus yellow',
    colors: {
      bgPrimary: '#fffef0',
      bgSecondary: '#fffce0',
      bgTertiary: '#fffad0',
      bgHover: '#fff8c0',
      textPrimary: '#665500',
      textSecondary: '#806a00',
      textTertiary: '#998000',
      borderPrimary: '#ffeb99',
      borderSecondary: '#ffe680',
      accent: '#ffd700',
      accentHover: '#e6c200',
      accentText: '#000000',
      success: '#ffd700',
      error: '#ff8c00',
      warning: '#ffeb3b',
      info: '#f4d03f',
      cardBg: '#fffff5',
      cardBorder: '#fffad0',
      cardShadow: 'rgba(255, 215, 0, 0.2)',
    },
  },

  light: {
    id: 'light',
    name: 'Light',
    description: 'Clean and bright',
    colors: {
      bgPrimary: '#ffffff',
      bgSecondary: '#f9fafb',
      bgTertiary: '#f3f4f6',
      bgHover: '#f3f4f6',
      
      textPrimary: '#111827',
      textSecondary: '#4b5563',
      textTertiary: '#9ca3af',
      
      borderPrimary: '#e5e7eb',
      borderSecondary: '#d1d5db',
      
      accent: '#3b82f6',
      accentHover: '#2563eb',
      accentText: '#ffffff',
      
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#3b82f6',
      
      cardBg: '#ffffff',
      cardBorder: '#e5e7eb',
      cardShadow: 'rgba(0, 0, 0, 0.1)',
    },
  },
  lilac: {
    id: 'lilac',
    name: 'Lilac',
    description: 'Soft lilac purple',
    colors: {
      bgPrimary: '#f5f0f8',
      bgSecondary: '#ebe0f0',
      bgTertiary: '#e0d0e8',
      bgHover: '#d6c0e0',
      textPrimary: '#4d334d',
      textSecondary: '#664766',
      textTertiary: '#805c80',
      borderPrimary: '#b393b3',
      borderSecondary: '#9e7a9e',
      accent: '#c8a2c8',
      accentHover: '#b088b0',
      accentText: '#ffffff',
      success: '#dda0dd',
      error: '#9370db',
      warning: '#c8a2c8',
      info: '#b088b0',
      cardBg: '#faf8fc',
      cardBorder: '#e0d0e8',
      cardShadow: 'rgba(200, 162, 200, 0.2)',
    },
  },

  lime: {
    id: 'lime',
    name: 'Lime Punch',
    description: 'Bright electric lime',
    colors: {
      bgPrimary: '#f7fee7',
      bgSecondary: '#ecfccb',
      bgTertiary: '#d9f99d',
      bgHover: '#ecfccb',
      textPrimary: '#365314',
      textSecondary: '#3f6212',
      textTertiary: '#4d7c0f',
      borderPrimary: '#bef264',
      borderSecondary: '#a3e635',
      accent: '#84cc16',
      accentHover: '#65a30d',
      accentText: '#ffffff',
      success: '#84cc16',
      error: '#ef4444',
      warning: '#eab308',
      info: '#3b82f6',
      cardBg: '#ffffff',
      cardBorder: '#bef264',
      cardShadow: 'rgba(132, 204, 22, 0.2)',
    },
  },
  
  magma: {
    id: 'magma',
    name: 'Magma',
    description: 'Volcanic heat',
    colors: {
      bgPrimary: '#1a0a00',
      bgSecondary: '#2d1400',
      bgTertiary: '#401e00',
      bgHover: '#532800',
      textPrimary: '#ffb380',
      textSecondary: '#ff9966',
      textTertiary: '#ff7f4d',
      borderPrimary: '#ff6633',
      borderSecondary: '#ff4d1a',
      accent: '#ff3300',
      accentHover: '#e62e00',
      accentText: '#ffffff',
      success: '#ffa500',
      error: '#ff0000',
      warning: '#ffcc00',
      info: '#ff6600',
      cardBg: '#2d1400',
      cardBorder: '#ff6633',
      cardShadow: 'rgba(255, 51, 0, 0.5)',
    },
  },

  mango: {
    id: 'mango',
    name: 'Mango Tango',
    description: 'Tropical mango orange',
    colors: {
      bgPrimary: '#fff8e6',
      bgSecondary: '#ffeecc',
      bgTertiary: '#ffe4b3',
      bgHover: '#ffda99',
      textPrimary: '#663d00',
      textSecondary: '#804d00',
      textTertiary: '#995c00',
      borderPrimary: '#ffc966',
      borderSecondary: '#ffbf4d',
      accent: '#ffb347',
      accentHover: '#ff9f1c',
      accentText: '#000000',
      success: '#ffa500',
      error: '#ff4500',
      warning: '#ffb347',
      info: '#ff8c00',
      cardBg: '#fffcf0',
      cardBorder: '#ffe4b3',
      cardShadow: 'rgba(255, 179, 71, 0.2)',
    },
  },

  maroon: {
    id: 'maroon',
    name: 'Maroon',
    description: 'Deep maroon red',
    colors: {
      bgPrimary: '#f0e6e8',
      bgSecondary: '#e0ccd1',
      bgTertiary: '#d0b3ba',
      bgHover: '#c099a3',
      textPrimary: '#4d1a1f',
      textSecondary: '#662d33',
      textTertiary: '#804047',
      borderPrimary: '#b36673',
      borderSecondary: '#9e4d5f',
      accent: '#800000',
      accentHover: '#660000',
      accentText: '#ffffff',
      success: '#a52a2a',
      error: '#8b0000',
      warning: '#cd5c5c',
      info: '#800000',
      cardBg: '#f8f5f6',
      cardBorder: '#d0b3ba',
      cardShadow: 'rgba(128, 0, 0, 0.2)',
    },
  },

  matrix: {
    id: 'matrix',
    name: 'Matrix',
    description: 'Green code rain',
    colors: {
      bgPrimary: '#0d0d0d',
      bgSecondary: '#1a1a1a',
      bgTertiary: '#262626',
      bgHover: '#333333',
      textPrimary: '#00ff41',
      textSecondary: '#00d936',
      textTertiary: '#00b32c',
      borderPrimary: '#008f11',
      borderSecondary: '#00ff41',
      accent: '#00ff41',
      accentHover: '#00d936',
      accentText: '#000000',
      success: '#00ff41',
      error: '#ff0033',
      warning: '#ffff00',
      info: '#00d4ff',
      cardBg: '#121212',
      cardBorder: '#008f11',
      cardShadow: 'rgba(0, 255, 65, 0.3)',
    },
  },
  
  meadow: {
    id: 'meadow',
    name: 'Spring Meadow',
    description: 'Fresh spring greens',
    colors: {
      bgPrimary: '#f0f8f0',
      bgSecondary: '#e0f0e0',
      bgTertiary: '#d0e8d0',
      bgHover: '#c0e0c0',
      textPrimary: '#1a4d1a',
      textSecondary: '#2d662d',
      textTertiary: '#408040',
      borderPrimary: '#80cc80',
      borderSecondary: '#66b366',
      accent: '#4caf50',
      accentHover: '#388e3c',
      accentText: '#ffffff',
      success: '#66bb6a',
      error: '#ef5350',
      warning: '#ffa726',
      info: '#42a5f5',
      cardBg: '#fafcfa',
      cardBorder: '#d0e8d0',
      cardShadow: 'rgba(76, 175, 80, 0.15)',
    },
  },

  midnight: {
    id: 'midnight',
    name: 'Midnight',
    description: 'Deep dark blue',
    colors: {
      bgPrimary: '#0a0e1a',
      bgSecondary: '#111827',
      bgTertiary: '#1f2937',
      bgHover: '#1f2937',
      
      textPrimary: '#e0e7ff',
      textSecondary: '#c7d2fe',
      textTertiary: '#a5b4fc',
      
      borderPrimary: '#1e3a8a',
      borderSecondary: '#2563eb',
      
      accent: '#6366f1',
      accentHover: '#4f46e5',
      accentText: '#ffffff',
      
      success: '#10b981',
      error: '#f87171',
      warning: '#fbbf24',
      info: '#60a5fa',
      
      cardBg: '#111827',
      cardBorder: '#1e3a8a',
      cardShadow: 'rgba(99, 102, 241, 0.1)',
    },
  },
  mint: {
    id: 'mint',
    name: 'Mint Fresh',
    description: 'Cool mint and green',
    colors: {
      bgPrimary: '#e6fff2',
      bgSecondary: '#b3ffd9',
      bgTertiary: '#80ffc0',
      bgHover: '#4dffa6',
      
      textPrimary: '#004d29',
      textSecondary: '#006633',
      textTertiary: '#008844',
      
      borderPrimary: '#1aff99',
      borderSecondary: '#00ff88',
      
      accent: '#00ff77',
      accentHover: '#00e66b',
      accentText: '#003322',
      
      success: '#00ff66',
      error: '#ff3366',
      warning: '#ffaa00',
      info: '#00bbff',
      
      cardBg: '#ffffff',
      cardBorder: '#66ffaa',
      cardShadow: 'rgba(0, 255, 119, 0.3)',
    },
  },
  
  // ADDITIONAL VIBRANT THEMES FOR FULL SPECTRUM
  mocha: {
    id: 'mocha',
    name: 'Mocha',
    description: 'Rich coffee tones',
    colors: {
      bgPrimary: '#1a1512',
      bgSecondary: '#2d2419',
      bgTertiary: '#3e3127',
      bgHover: '#3e3127',
      
      textPrimary: '#f5f1e8',
      textSecondary: '#d4c5b0',
      textTertiary: '#b8a68f',
      
      borderPrimary: '#3e3127',
      borderSecondary: '#8b6f47',
      
      accent: '#d4a574',
      accentHover: '#c49563',
      accentText: '#1a1512',
      
      success: '#82b74b',
      error: '#e05d44',
      warning: '#f0ad4e',
      info: '#6fa8dc',
      
      cardBg: '#2d2419',
      cardBorder: '#3e3127',
      cardShadow: 'rgba(212, 165, 116, 0.1)',
    },
  },
  monsoon: {
    id: 'monsoon',
    name: 'Monsoon',
    description: 'Rainy day blues',
    colors: {
      bgPrimary: '#1a2633',
      bgSecondary: '#243342',
      bgTertiary: '#2e4051',
      bgHover: '#384d60',
      textPrimary: '#d5e0eb',
      textSecondary: '#bfcfdf',
      textTertiary: '#a9bed3',
      borderPrimary: '#5a7a99',
      borderSecondary: '#4a6a89',
      accent: '#4a90a4',
      accentHover: '#3a7084',
      accentText: '#ffffff',
      success: '#5f9ea0',
      error: '#b22222',
      warning: '#4682b4',
      info: '#4a90a4',
      cardBg: '#243342',
      cardBorder: '#5a7a99',
      cardShadow: 'rgba(74, 144, 164, 0.3)',
    },
  },

  mulberry: {
    id: 'mulberry',
    name: 'Mulberry',
    description: 'Deep berry purple',
    colors: {
      bgPrimary: '#f0e6f0',
      bgSecondary: '#e0cce0',
      bgTertiary: '#d0b3d0',
      bgHover: '#c099c0',
      textPrimary: '#4d1a4d',
      textSecondary: '#662d66',
      textTertiary: '#804080',
      borderPrimary: '#b366b3',
      borderSecondary: '#9e4d9e',
      accent: '#8b008b',
      accentHover: '#6b006b',
      accentText: '#ffffff',
      success: '#9370db',
      error: '#dc143c',
      warning: '#ba55d3',
      info: '#8b008b',
      cardBg: '#f8f5f8',
      cardBorder: '#d0b3d0',
      cardShadow: 'rgba(139, 0, 139, 0.2)',
    },
  },

  navy: {
    id: 'navy',
    name: 'Navy',
    description: 'Deep navy blue',
    colors: {
      bgPrimary: '#172554',
      bgSecondary: '#1e3a8a',
      bgTertiary: '#1e40af',
      bgHover: '#1e3a8a',
      textPrimary: '#dbeafe',
      textSecondary: '#bfdbfe',
      textTertiary: '#93c5fd',
      borderPrimary: '#1e40af',
      borderSecondary: '#2563eb',
      accent: '#3b82f6',
      accentHover: '#2563eb',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#60a5fa',
      cardBg: '#1e3a8a',
      cardBorder: '#2563eb',
      cardShadow: 'rgba(59, 130, 246, 0.3)',
    },
  },
  
  neon: {
    id: 'neon',
    name: 'Neon Lights',
    description: 'Electric neon colors',
    colors: {
      bgPrimary: '#0a0a0a',
      bgSecondary: '#1a1a1a',
      bgTertiary: '#2a2a2a',
      bgHover: '#333333',
      textPrimary: '#00ff9f',
      textSecondary: '#00e5ff',
      textTertiary: '#ff00ff',
      borderPrimary: '#00ff9f',
      borderSecondary: '#00e5ff',
      accent: '#ff00ff',
      accentHover: '#ff3fff',
      accentText: '#000000',
      success: '#00ff9f',
      error: '#ff0055',
      warning: '#ffff00',
      info: '#00e5ff',
      cardBg: '#141414',
      cardBorder: '#00ff9f',
      cardShadow: 'rgba(0, 255, 159, 0.3)',
    },
  },
  
  nightshade: {
    id: 'nightshade',
    name: 'Nightshade',
    description: 'Deep purple darkness',
    colors: {
      bgPrimary: '#1a0d26',
      bgSecondary: '#2d1a3d',
      bgTertiary: '#402654',
      bgHover: '#53336b',
      textPrimary: '#e0d0f0',
      textSecondary: '#d0b8e6',
      textTertiary: '#c0a0dc',
      borderPrimary: '#8060a8',
      borderSecondary: '#6d4d95',
      accent: '#6a0dad',
      accentHover: '#550a8a',
      accentText: '#ffffff',
      success: '#9370db',
      error: '#8b008b',
      warning: '#ba55d3',
      info: '#6a0dad',
      cardBg: '#2d1a3d',
      cardBorder: '#8060a8',
      cardShadow: 'rgba(106, 13, 173, 0.4)',
    },
  },

  noire: {
    id: 'noire',
    name: 'Film Noire',
    description: 'Classic black and white',
    colors: {
      bgPrimary: '#1c1c1c',
      bgSecondary: '#2e2e2e',
      bgTertiary: '#404040',
      bgHover: '#525252',
      textPrimary: '#f0f0f0',
      textSecondary: '#d0d0d0',
      textTertiary: '#b0b0b0',
      borderPrimary: '#606060',
      borderSecondary: '#707070',
      accent: '#ffffff',
      accentHover: '#e0e0e0',
      accentText: '#000000',
      success: '#a0a0a0',
      error: '#808080',
      warning: '#909090',
      info: '#b0b0b0',
      cardBg: '#2e2e2e',
      cardBorder: '#606060',
      cardShadow: 'rgba(255, 255, 255, 0.1)',
    },
  },

  nord: {
    id: 'nord',
    name: 'Nord',
    description: 'Arctic inspired',
    colors: {
      bgPrimary: '#2e3440',
      bgSecondary: '#3b4252',
      bgTertiary: '#434c5e',
      bgHover: '#434c5e',
      
      textPrimary: '#eceff4',
      textSecondary: '#e5e9f0',
      textTertiary: '#d8dee9',
      
      borderPrimary: '#434c5e',
      borderSecondary: '#4c566a',
      
      accent: '#88c0d0',
      accentHover: '#81a1c1',
      accentText: '#2e3440',
      
      success: '#a3be8c',
      error: '#bf616a',
      warning: '#ebcb8b',
      info: '#5e81ac',
      
      cardBg: '#3b4252',
      cardBorder: '#434c5e',
      cardShadow: 'rgba(136, 192, 208, 0.1)',
    },
  },
  ocean: {
    id: 'ocean',
    name: 'Ocean',
    description: 'Deep blue waters',
    colors: {
      bgPrimary: '#0c1821',
      bgSecondary: '#1b2838',
      bgTertiary: '#2c3e50',
      bgHover: '#2c3e50',
      
      textPrimary: '#ecf0f1',
      textSecondary: '#bdc3c7',
      textTertiary: '#95a5a6',
      
      borderPrimary: '#2c3e50',
      borderSecondary: '#3498db',
      
      accent: '#3498db',
      accentHover: '#2980b9',
      accentText: '#ffffff',
      
      success: '#1abc9c',
      error: '#e74c3c',
      warning: '#f39c12',
      info: '#3498db',
      
      cardBg: '#1b2838',
      cardBorder: '#2c3e50',
      cardShadow: 'rgba(52, 152, 219, 0.1)',
    },
  },
  olive: {
    id: 'olive',
    name: 'Olive',
    description: 'Earthy olive green',
    colors: {
      bgPrimary: '#f7fee7',
      bgSecondary: '#ecfccb',
      bgTertiary: '#d9f99d',
      bgHover: '#ecfccb',
      textPrimary: '#365314',
      textSecondary: '#3f6212',
      textTertiary: '#4d7c0f',
      borderPrimary: '#bef264',
      borderSecondary: '#a3e635',
      accent: '#84cc16',
      accentHover: '#65a30d',
      accentText: '#ffffff',
      success: '#84cc16',
      error: '#ef4444',
      warning: '#eab308',
      info: '#3b82f6',
      cardBg: '#ffffff',
      cardBorder: '#bef264',
      cardShadow: 'rgba(132, 204, 22, 0.2)',
    },
  },
  
  // PRIMARY COLOR VARIATIONS - PURPLES
  orchid: {
    id: 'orchid',
    name: 'Orchid',
    description: 'Elegant orchid purple',
    colors: {
      bgPrimary: '#f5e6f5',
      bgSecondary: '#ebcceb',
      bgTertiary: '#e0b3e0',
      bgHover: '#d699d6',
      textPrimary: '#4d1a4d',
      textSecondary: '#662d66',
      textTertiary: '#804080',
      borderPrimary: '#b366b3',
      borderSecondary: '#9e4d9e',
      accent: '#da70d6',
      accentHover: '#ba55d3',
      accentText: '#ffffff',
      success: '#dda0dd',
      error: '#8b008b',
      warning: '#ee82ee',
      info: '#da70d6',
      cardBg: '#faf5fa',
      cardBorder: '#e0b3e0',
      cardShadow: 'rgba(218, 112, 214, 0.2)',
    },
  },

  papaya: {
    id: 'papaya',
    name: 'Papaya Punch',
    description: 'Tropical fruit vibes',
    colors: {
      bgPrimary: '#fff4e6',
      bgSecondary: '#ffe4cc',
      bgTertiary: '#ffd4b3',
      bgHover: '#ffc499',
      textPrimary: '#663300',
      textSecondary: '#804000',
      textTertiary: '#994d00',
      borderPrimary: '#ffb380',
      borderSecondary: '#ffa366',
      accent: '#ff8c42',
      accentHover: '#ff7629',
      accentText: '#ffffff',
      success: '#ff8c42',
      error: '#ff6347',
      warning: '#ffa500',
      info: '#ff7f50',
      cardBg: '#fffaf5',
      cardBorder: '#ffd4b3',
      cardShadow: 'rgba(255, 140, 66, 0.2)',
    },
  },

  peach: {
    id: 'peach',
    name: 'Peach',
    description: 'Soft warm peach',
    colors: {
      bgPrimary: '#fff5f0',
      bgSecondary: '#ffe5d9',
      bgTertiary: '#ffd4b8',
      bgHover: '#ffe5d9',
      textPrimary: '#7c3a14',
      textSecondary: '#a44a1a',
      textTertiary: '#c85a20',
      borderPrimary: '#ffb999',
      borderSecondary: '#ff9d6b',
      accent: '#ff7f3f',
      accentHover: '#ff6624',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#ff7f3f',
      info: '#3b82f6',
      cardBg: '#ffffff',
      cardBorder: '#ffb999',
      cardShadow: 'rgba(255, 127, 63, 0.2)',
    },
  },
  
  periwinkle: {
    id: 'periwinkle',
    name: 'Periwinkle',
    description: 'Soft periwinkle blue',
    colors: {
      bgPrimary: '#f0f0f8',
      bgSecondary: '#e0e0f0',
      bgTertiary: '#d0d0e8',
      bgHover: '#c0c0e0',
      textPrimary: '#33334d',
      textSecondary: '#474766',
      textTertiary: '#5c5c80',
      borderPrimary: '#9393b3',
      borderSecondary: '#7a7a9e',
      accent: '#ccccff',
      accentHover: '#b3b3f5',
      accentText: '#33334d',
      success: '#b0c4de',
      error: '#9370db',
      warning: '#ccccff',
      info: '#6495ed',
      cardBg: '#f8f8fc',
      cardBorder: '#d0d0e8',
      cardShadow: 'rgba(204, 204, 255, 0.3)',
    },
  },

  pewter: {
    id: 'pewter',
    name: 'Pewter',
    description: 'Metallic gray-blue',
    colors: {
      bgPrimary: '#e8eaed',
      bgSecondary: '#d4d8dd',
      bgTertiary: '#c0c6cd',
      bgHover: '#acb4bd',
      textPrimary: '#1a2633',
      textSecondary: '#2d3947',
      textTertiary: '#404d5c',
      borderPrimary: '#8a96a3',
      borderSecondary: '#707d8a',
      accent: '#5c6b7a',
      accentHover: '#4a5866',
      accentText: '#ffffff',
      success: '#708090',
      error: '#696969',
      warning: '#b0c4de',
      info: '#5c6b7a',
      cardBg: '#f5f6f8',
      cardBorder: '#c0c6cd',
      cardShadow: 'rgba(92, 107, 122, 0.2)',
    },
  },

  pistachio: {
    id: 'pistachio',
    name: 'Pistachio',
    description: 'Soft nutty green',
    colors: {
      bgPrimary: '#f0f5e8',
      bgSecondary: '#e0ebd0',
      bgTertiary: '#d0e1b8',
      bgHover: '#c0d7a0',
      textPrimary: '#334d1a',
      textSecondary: '#47662d',
      textTertiary: '#5c8040',
      borderPrimary: '#93b373',
      borderSecondary: '#7a9e5f',
      accent: '#93c572',
      accentHover: '#7ab05a',
      accentText: '#ffffff',
      success: '#93c572',
      error: '#8b4513',
      warning: '#f0e68c',
      info: '#6b8e23',
      cardBg: '#f8faf5',
      cardBorder: '#d0e1b8',
      cardShadow: 'rgba(147, 197, 114, 0.2)',
    },
  },

  plum: {
    id: 'plum',
    name: 'Plum',
    description: 'Deep purple plum',
    colors: {
      bgPrimary: '#faf5ff',
      bgSecondary: '#f3e8ff',
      bgTertiary: '#e9d5ff',
      bgHover: '#f3e8ff',
      textPrimary: '#4c1d95',
      textSecondary: '#5b21b6',
      textTertiary: '#6d28d9',
      borderPrimary: '#c084fc',
      borderSecondary: '#a855f7',
      accent: '#8b5cf6',
      accentHover: '#7c3aed',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#8b5cf6',
      cardBg: '#ffffff',
      cardBorder: '#c084fc',
      cardShadow: 'rgba(139, 92, 246, 0.2)',
    },
  },
  
  pumpkin: {
    id: 'pumpkin',
    name: 'Pumpkin Spice',
    description: 'Autumn harvest orange',
    colors: {
      bgPrimary: '#fff5e6',
      bgSecondary: '#ffe5cc',
      bgTertiary: '#ffd5b3',
      bgHover: '#ffc599',
      textPrimary: '#663300',
      textSecondary: '#804000',
      textTertiary: '#994d00',
      borderPrimary: '#ffb366',
      borderSecondary: '#ffa34d',
      accent: '#ff8c00',
      accentHover: '#e67300',
      accentText: '#ffffff',
      success: '#ff8c00',
      error: '#8b0000',
      warning: '#ffa34d',
      info: '#d2691e',
      cardBg: '#fffaf0',
      cardBorder: '#ffd5b3',
      cardShadow: 'rgba(255, 140, 0, 0.2)',
    },
  },

  raspberry: {
    id: 'raspberry',
    name: 'Raspberry',
    description: 'Tart raspberry red',
    colors: {
      bgPrimary: '#f5e6eb',
      bgSecondary: '#ebccd6',
      bgTertiary: '#e0b3c2',
      bgHover: '#d699ad',
      textPrimary: '#4d1a26',
      textSecondary: '#662d39',
      textTertiary: '#80404d',
      borderPrimary: '#b36680',
      borderSecondary: '#9e4d6b',
      accent: '#c71585',
      accentHover: '#a0116a',
      accentText: '#ffffff',
      success: '#ff69b4',
      error: '#8b0000',
      warning: '#ff1493',
      info: '#c71585',
      cardBg: '#faf5f7',
      cardBorder: '#e0b3c2',
      cardShadow: 'rgba(199, 21, 133, 0.2)',
    },
  },

  redwood: {
    id: 'redwood',
    name: 'Redwood',
    description: 'Deep forest red',
    colors: {
      bgPrimary: '#3d1a1a',
      bgSecondary: '#522424',
      bgTertiary: '#662e2e',
      bgHover: '#7a3838',
      textPrimary: '#f2d5d5',
      textSecondary: '#e6bfbf',
      textTertiary: '#daa9a9',
      borderPrimary: '#a85757',
      borderSecondary: '#9c4343',
      accent: '#a0522d',
      accentHover: '#8b4513',
      accentText: '#ffffff',
      success: '#cd853f',
      error: '#8b0000',
      warning: '#d2691e',
      info: '#a0522d',
      cardBg: '#522424',
      cardBorder: '#a85757',
      cardShadow: 'rgba(160, 82, 45, 0.3)',
    },
  },

  rose: {
    id: 'rose',
    name: 'Rose Garden',
    description: 'Elegant rose pink',
    colors: {
      bgPrimary: '#fff1f2',
      bgSecondary: '#ffe4e6',
      bgTertiary: '#fecdd3',
      bgHover: '#ffe4e6',
      textPrimary: '#881337',
      textSecondary: '#9f1239',
      textTertiary: '#be123c',
      borderPrimary: '#fda4af',
      borderSecondary: '#fb7185',
      accent: '#f43f5e',
      accentHover: '#e11d48',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#f43f5e',
      warning: '#f59e0b',
      info: '#ec4899',
      cardBg: '#ffffff',
      cardBorder: '#fda4af',
      cardShadow: 'rgba(244, 63, 94, 0.2)',
    },
  },
  
  royal: {
    id: 'royal',
    name: 'Royal Purple',
    description: 'Majestic deep purple',
    colors: {
      bgPrimary: '#faf5ff',
      bgSecondary: '#f3e8ff',
      bgTertiary: '#e9d5ff',
      bgHover: '#f3e8ff',
      textPrimary: '#581c87',
      textSecondary: '#6b21a8',
      textTertiary: '#7c3aed',
      borderPrimary: '#d8b4fe',
      borderSecondary: '#c084fc',
      accent: '#9333ea',
      accentHover: '#7c3aed',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#8b5cf6',
      cardBg: '#ffffff',
      cardBorder: '#d8b4fe',
      cardShadow: 'rgba(147, 51, 234, 0.2)',
    },
  },
  
  ruby: {
    id: 'ruby',
    name: 'Ruby',
    description: 'Deep ruby red',
    colors: {
      bgPrimary: '#fef2f2',
      bgSecondary: '#fee2e2',
      bgTertiary: '#fecaca',
      bgHover: '#fee2e2',
      textPrimary: '#7f1d1d',
      textSecondary: '#991b1b',
      textTertiary: '#b91c1c',
      borderPrimary: '#fca5a5',
      borderSecondary: '#f87171',
      accent: '#dc2626',
      accentHover: '#b91c1c',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#dc2626',
      warning: '#f59e0b',
      info: '#3b82f6',
      cardBg: '#ffffff',
      cardBorder: '#fca5a5',
      cardShadow: 'rgba(220, 38, 38, 0.2)',
    },
  },
  
  rust: {
    id: 'rust',
    name: 'Rust',
    description: 'Deep rust orange',
    colors: {
      bgPrimary: '#7c2d12',
      bgSecondary: '#9a3412',
      bgTertiary: '#c2410c',
      bgHover: '#9a3412',
      textPrimary: '#fed7aa',
      textSecondary: '#fdba74',
      textTertiary: '#fb923c',
      borderPrimary: '#c2410c',
      borderSecondary: '#ea580c',
      accent: '#f97316',
      accentHover: '#ea580c',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#fb923c',
      cardBg: '#9a3412',
      cardBorder: '#c2410c',
      cardShadow: 'rgba(249, 115, 22, 0.3)',
    },
  },
  
  // PRIMARY COLOR VARIATIONS - PINKS
  sand: {
    id: 'sand',
    name: 'Sand',
    description: 'Warm sandy beige',
    colors: {
      bgPrimary: '#fefce8',
      bgSecondary: '#fef9c3',
      bgTertiary: '#fef08a',
      bgHover: '#fef9c3',
      textPrimary: '#713f12',
      textSecondary: '#854d0e',
      textTertiary: '#a16207',
      borderPrimary: '#fde047',
      borderSecondary: '#facc15',
      accent: '#eab308',
      accentHover: '#ca8a04',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#eab308',
      info: '#3b82f6',
      cardBg: '#ffffff',
      cardBorder: '#fde047',
      cardShadow: 'rgba(234, 179, 8, 0.2)',
    },
  },
  
  sapphire: {
    id: 'sapphire',
    name: 'Sapphire',
    description: 'Deep brilliant blue',
    colors: {
      bgPrimary: '#eff6ff',
      bgSecondary: '#dbeafe',
      bgTertiary: '#bfdbfe',
      bgHover: '#dbeafe',
      textPrimary: '#1e3a8a',
      textSecondary: '#1e40af',
      textTertiary: '#2563eb',
      borderPrimary: '#93c5fd',
      borderSecondary: '#60a5fa',
      accent: '#3b82f6',
      accentHover: '#2563eb',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#3b82f6',
      cardBg: '#ffffff',
      cardBorder: '#93c5fd',
      cardShadow: 'rgba(59, 130, 246, 0.25)',
    },
  },
  
  seafoam: {
    id: 'seafoam',
    name: 'Seafoam',
    description: 'Ocean foam green',
    colors: {
      bgPrimary: '#e6f9f5',
      bgSecondary: '#ccf2e8',
      bgTertiary: '#b3ecdc',
      bgHover: '#99e6cf',
      textPrimary: '#00404d',
      textSecondary: '#005966',
      textTertiary: '#007380',
      borderPrimary: '#66d9c2',
      borderSecondary: '#4dd2b5',
      accent: '#2e8b57',
      accentHover: '#247046',
      accentText: '#ffffff',
      success: '#3cb371',
      error: '#cd5c5c',
      warning: '#20b2aa',
      info: '#2e8b57',
      cardBg: '#f5fcfa',
      cardBorder: '#b3ecdc',
      cardShadow: 'rgba(46, 139, 87, 0.2)',
    },
  },

  sky: {
    id: 'sky',
    name: 'Sky High',
    description: 'Bright blue skies',
    colors: {
      bgPrimary: '#f0f8ff',
      bgSecondary: '#d4ecff',
      bgTertiary: '#b8e0ff',
      bgHover: '#9cd4ff',
      
      textPrimary: '#002855',
      textSecondary: '#004080',
      textTertiary: '#0058aa',
      
      borderPrimary: '#80c8ff',
      borderSecondary: '#64bcff',
      
      accent: '#0ea5e9',
      accentHover: '#0284c7',
      accentText: '#ffffff',
      
      success: '#22c55e',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#3b82f6',
      
      cardBg: '#ffffff',
      cardBorder: '#a4d8ff',
      cardShadow: 'rgba(14, 165, 233, 0.15)',
    },
  },
  skyBlue: {
    id: 'skyBlue',
    name: 'Sky Blue',
    description: 'Light sky blue',
    colors: {
      bgPrimary: '#e0f2fe',
      bgSecondary: '#bae6fd',
      bgTertiary: '#7dd3fc',
      bgHover: '#bae6fd',
      textPrimary: '#075985',
      textSecondary: '#0c4a6e',
      textTertiary: '#0369a1',
      borderPrimary: '#38bdf8',
      borderSecondary: '#0ea5e9',
      accent: '#0284c7',
      accentHover: '#0369a1',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#0284c7',
      cardBg: '#ffffff',
      cardBorder: '#38bdf8',
      cardShadow: 'rgba(2, 132, 199, 0.2)',
    },
  },
  
  slate: {
    id: 'slate',
    name: 'Slate',
    description: 'Cool gray tones',
    colors: {
      bgPrimary: '#f8fafc',
      bgSecondary: '#f1f5f9',
      bgTertiary: '#e2e8f0',
      bgHover: '#f1f5f9',
      textPrimary: '#0f172a',
      textSecondary: '#334155',
      textTertiary: '#64748b',
      borderPrimary: '#cbd5e1',
      borderSecondary: '#94a3b8',
      accent: '#3b82f6',
      accentHover: '#2563eb',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#3b82f6',
      cardBg: '#ffffff',
      cardBorder: '#cbd5e1',
      cardShadow: 'rgba(100, 116, 139, 0.1)',
    },
  },
  
  solarized: {
    id: 'solarized',
    name: 'Solarized Dark',
    description: 'Easy on the eyes',
    colors: {
      bgPrimary: '#002b36',
      bgSecondary: '#073642',
      bgTertiary: '#586e75',
      bgHover: '#586e75',
      
      textPrimary: '#fdf6e3',
      textSecondary: '#eee8d5',
      textTertiary: '#93a1a1',
      
      borderPrimary: '#073642',
      borderSecondary: '#586e75',
      
      accent: '#268bd2',
      accentHover: '#2176b3',
      accentText: '#fdf6e3',
      
      success: '#859900',
      error: '#dc322f',
      warning: '#b58900',
      info: '#268bd2',
      
      cardBg: '#073642',
      cardBorder: '#586e75',
      cardShadow: 'rgba(38, 139, 210, 0.1)',
    },
  },
  steel: {
    id: 'steel',
    name: 'Steel Blue',
    description: 'Cool steel tones',
    colors: {
      bgPrimary: '#f1f5f9',
      bgSecondary: '#e2e8f0',
      bgTertiary: '#cbd5e1',
      bgHover: '#e2e8f0',
      textPrimary: '#0f172a',
      textSecondary: '#334155',
      textTertiary: '#475569',
      borderPrimary: '#94a3b8',
      borderSecondary: '#64748b',
      accent: '#475569',
      accentHover: '#334155',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#3b82f6',
      cardBg: '#ffffff',
      cardBorder: '#cbd5e1',
      cardShadow: 'rgba(71, 85, 105, 0.15)',
    },
  },
  
  // PRIMARY COLOR VARIATIONS - REDS
  storm: {
    id: 'storm',
    name: 'Thunderstorm',
    description: 'Dark stormy skies',
    colors: {
      bgPrimary: '#1a1a26',
      bgSecondary: '#2d2d3d',
      bgTertiary: '#404054',
      bgHover: '#53536b',
      textPrimary: '#d5d5e0',
      textSecondary: '#bfbfd0',
      textTertiary: '#a9a9c0',
      borderPrimary: '#6b6b8a',
      borderSecondary: '#57577a',
      accent: '#4169e1',
      accentHover: '#3355c7',
      accentText: '#ffffff',
      success: '#4169e1',
      error: '#ff6347',
      warning: '#ffd700',
      info: '#87ceeb',
      cardBg: '#2d2d3d',
      cardBorder: '#6b6b8a',
      cardShadow: 'rgba(65, 105, 225, 0.3)',
    },
  },

  sunrise: {
    id: 'sunrise',
    name: 'Sunrise',
    description: 'Warm sunrise gradient',
    colors: {
      bgPrimary: '#fff1f2',
      bgSecondary: '#ffe4e6',
      bgTertiary: '#fecdd3',
      bgHover: '#ffe4e6',
      textPrimary: '#881337',
      textSecondary: '#9f1239',
      textTertiary: '#be123c',
      borderPrimary: '#fda4af',
      borderSecondary: '#fb7185',
      accent: '#f43f5e',
      accentHover: '#e11d48',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#f43f5e',
      warning: '#fb923c',
      info: '#3b82f6',
      cardBg: '#ffffff',
      cardBorder: '#fda4af',
      cardShadow: 'rgba(244, 63, 94, 0.2)',
    },
  },
  
  sunset: {
    id: 'sunset',
    name: 'Sunset',
    description: 'Warm orange and pink',
    colors: {
      bgPrimary: '#1a0a0f',
      bgSecondary: '#431407',
      bgTertiary: '#7c2d12',
      bgHover: '#7c2d12',
      
      textPrimary: '#fff7ed',
      textSecondary: '#fed7aa',
      textTertiary: '#fdba74',
      
      borderPrimary: '#7c2d12',
      borderSecondary: '#ea580c',
      
      accent: '#f97316',
      accentHover: '#ea580c',
      accentText: '#ffffff',
      
      success: '#10b981',
      error: '#ef4444',
      warning: '#fbbf24',
      info: '#3b82f6',
      
      cardBg: '#431407',
      cardBorder: '#7c2d12',
      cardShadow: 'rgba(249, 115, 22, 0.1)',
    },
  },
  tangerine: {
    id: 'tangerine',
    name: 'Tangerine',
    description: 'Bright orange energy',
    colors: {
      bgPrimary: '#fff5e6',
      bgSecondary: '#ffe0b3',
      bgTertiary: '#ffcc80',
      bgHover: '#ffb84d',
      
      textPrimary: '#4d2600',
      textSecondary: '#663300',
      textTertiary: '#804000',
      
      borderPrimary: '#ffa64d',
      borderSecondary: '#ff9933',
      
      accent: '#ff8800',
      accentHover: '#ff6600',
      accentText: '#ffffff',
      
      success: '#00ff66',
      error: '#ff3333',
      warning: '#ffcc00',
      info: '#0099ff',
      
      cardBg: '#ffffff',
      cardBorder: '#ffb366',
      cardShadow: 'rgba(255, 136, 0, 0.3)',
    },
  },
  tangerineOrange: {
    id: 'tangerineOrange',
    name: 'Tangerine Orange',
    description: 'Bright tangerine',
    colors: {
      bgPrimary: '#fff7ed',
      bgSecondary: '#ffedd5',
      bgTertiary: '#fed7aa',
      bgHover: '#ffedd5',
      textPrimary: '#7c2d12',
      textSecondary: '#9a3412',
      textTertiary: '#c2410c',
      borderPrimary: '#fdba74',
      borderSecondary: '#fb923c',
      accent: '#f97316',
      accentHover: '#ea580c',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#dc2626',
      warning: '#f97316',
      info: '#3b82f6',
      cardBg: '#ffffff',
      cardBorder: '#fdba74',
      cardShadow: 'rgba(249, 115, 22, 0.2)',
    },
  },
  
  teal: {
    id: 'teal',
    name: 'Teal Wave',
    description: 'Vibrant teal and cyan',
    colors: {
      bgPrimary: '#f0fdfa',
      bgSecondary: '#ccfbf1',
      bgTertiary: '#99f6e4',
      bgHover: '#ccfbf1',
      textPrimary: '#134e4a',
      textSecondary: '#115e59',
      textTertiary: '#0f766e',
      borderPrimary: '#5eead4',
      borderSecondary: '#2dd4bf',
      accent: '#14b8a6',
      accentHover: '#0d9488',
      accentText: '#ffffff',
      success: '#14b8a6',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#06b6d4',
      cardBg: '#ffffff',
      cardBorder: '#5eead4',
      cardShadow: 'rgba(20, 184, 166, 0.2)',
    },
  },
  
  turquoise: {
    id: 'turquoise',
    name: 'Turquoise',
    description: 'Bright turquoise',
    colors: {
      bgPrimary: '#ecfeff',
      bgSecondary: '#cffafe',
      bgTertiary: '#a5f3fc',
      bgHover: '#cffafe',
      textPrimary: '#164e63',
      textSecondary: '#155e75',
      textTertiary: '#0e7490',
      borderPrimary: '#67e8f9',
      borderSecondary: '#22d3ee',
      accent: '#06b6d4',
      accentHover: '#0891b2',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#06b6d4',
      cardBg: '#ffffff',
      cardBorder: '#67e8f9',
      cardShadow: 'rgba(6, 182, 212, 0.2)',
    },
  },
  
  twilight: {
    id: 'twilight',
    name: 'Twilight',
    description: 'Purple twilight sky',
    colors: {
      bgPrimary: '#2e1065',
      bgSecondary: '#4c1d95',
      bgTertiary: '#5b21b6',
      bgHover: '#4c1d95',
      textPrimary: '#e9d5ff',
      textSecondary: '#d8b4fe',
      textTertiary: '#c084fc',
      borderPrimary: '#6d28d9',
      borderSecondary: '#7c3aed',
      accent: '#8b5cf6',
      accentHover: '#7c3aed',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#a855f7',
      cardBg: '#4c1d95',
      cardBorder: '#6d28d9',
      cardShadow: 'rgba(139, 92, 246, 0.3)',
    },
  },
  
  vaporwave: {
    id: 'vaporwave',
    name: 'Vaporwave',
    description: 'Retro 80s aesthetic',
    colors: {
      bgPrimary: '#1a0033',
      bgSecondary: '#2d0052',
      bgTertiary: '#400070',
      bgHover: '#2d0052',
      textPrimary: '#ff71ce',
      textSecondary: '#01cdfe',
      textTertiary: '#b967ff',
      borderPrimary: '#05ffa1',
      borderSecondary: '#fffb96',
      accent: '#ff6c11',
      accentHover: '#ff4500',
      accentText: '#ffffff',
      success: '#ff71ce',
      error: '#ff006e',
      warning: '#fffb96',
      info: '#01cdfe',
      cardBg: '#2d0052',
      cardBorder: '#b967ff',
      cardShadow: 'rgba(255, 113, 206, 0.4)',
    },
  },

  violet: {
    id: 'violet',
    name: 'Violet',
    description: 'Deep violet purple',
    colors: {
      bgPrimary: '#faf5ff',
      bgSecondary: '#f3e8ff',
      bgTertiary: '#e9d5ff',
      bgHover: '#f3e8ff',
      textPrimary: '#581c87',
      textSecondary: '#6b21a8',
      textTertiary: '#7c3aed',
      borderPrimary: '#d8b4fe',
      borderSecondary: '#c084fc',
      accent: '#a855f7',
      accentHover: '#9333ea',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#a855f7',
      cardBg: '#ffffff',
      cardBorder: '#d8b4fe',
      cardShadow: 'rgba(168, 85, 247, 0.2)',
    },
  },
  
  volcano: {
    id: 'volcano',
    name: 'Volcano',
    description: 'Fiery orange and red',
    colors: {
      bgPrimary: '#fff7ed',
      bgSecondary: '#ffedd5',
      bgTertiary: '#fed7aa',
      bgHover: '#ffedd5',
      textPrimary: '#7c2d12',
      textSecondary: '#9a3412',
      textTertiary: '#c2410c',
      borderPrimary: '#fdba74',
      borderSecondary: '#fb923c',
      accent: '#f97316',
      accentHover: '#ea580c',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#dc2626',
      warning: '#f97316',
      info: '#3b82f6',
      cardBg: '#ffffff',
      cardBorder: '#fdba74',
      cardShadow: 'rgba(249, 115, 22, 0.25)',
    },
  },
  
  watermelon: {
    id: 'watermelon',
    name: 'Watermelon',
    description: 'Fresh summer fruit',
    colors: {
      bgPrimary: '#fff5f7',
      bgSecondary: '#ffe5ea',
      bgTertiary: '#ffd5dd',
      bgHover: '#ffc5d0',
      textPrimary: '#661a26',
      textSecondary: '#802d39',
      textTertiary: '#99404d',
      borderPrimary: '#ff99aa',
      borderSecondary: '#ff8099',
      accent: '#ff6b81',
      accentHover: '#ff4757',
      accentText: '#ffffff',
      success: '#7bed9f',
      error: '#ff4757',
      warning: '#ffa502',
      info: '#70a1ff',
      cardBg: '#fffafc',
      cardBorder: '#ffd5dd',
      cardShadow: 'rgba(255, 107, 129, 0.2)',
    },
  },

  wine: {
    id: 'wine',
    name: 'Wine',
    description: 'Rich wine red',
    colors: {
      bgPrimary: '#4c0519',
      bgSecondary: '#7f1d1d',
      bgTertiary: '#991b1b',
      bgHover: '#7f1d1d',
      textPrimary: '#fecaca',
      textSecondary: '#fca5a5',
      textTertiary: '#f87171',
      borderPrimary: '#991b1b',
      borderSecondary: '#b91c1c',
      accent: '#dc2626',
      accentHover: '#b91c1c',
      accentText: '#ffffff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#f87171',
      cardBg: '#7f1d1d',
      cardBorder: '#991b1b',
      cardShadow: 'rgba(220, 38, 38, 0.3)',
    },
  },
  
  // PRIMARY COLOR VARIATIONS - GREENS
};

interface ThemeContextType {
  currentTheme: string;
  theme: Theme;
  setTheme: (themeId: string) => void;
  availableThemes: Theme[];
  customThemes: Theme[];
  createCustomTheme: (theme: Theme) => void;
  updateCustomTheme: (theme: Theme) => void;
  deleteCustomTheme: (themeId: string) => void;
  isBuiltInTheme: (themeId: string) => boolean;
  isThemeModified: (themeId: string) => boolean;
  restoreThemeToDefault: (themeId: string) => void;
  getDefaultTheme: (themeId: string) => Theme | null;
}

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

export const useTheme = () => {
  const context = useContext(ThemeContext);
  if (!context) {
    throw new Error('useTheme must be used within a ThemeProvider');
  }
  return context;
};

interface ThemeProviderProps {
  children: ReactNode;
}

// Load custom themes from localStorage
const loadCustomThemes = (): Theme[] => {
  try {
    const stored = localStorage.getItem('custom-themes');
    return stored ? JSON.parse(stored) : [];
  } catch (error) {
    console.error('Failed to load custom themes:', error);
    return [];
  }
};

// Save custom themes to localStorage
const saveCustomThemes = (themes: Theme[]) => {
  try {
    localStorage.setItem('custom-themes', JSON.stringify(themes));
  } catch (error) {
    console.error('Failed to save custom themes:', error);
  }
};

export const ThemeProvider: React.FC<ThemeProviderProps> = ({ children }) => {
  const [currentTheme, setCurrentTheme] = useState<string>(() => {
    // Load theme from localStorage or default to 'light'
    return localStorage.getItem('app-theme') || 'light';
  });

  const [customThemes, setCustomThemes] = useState<Theme[]>(() => loadCustomThemes());

  // Combine built-in and custom themes (memoized to prevent unnecessary recalculations)
  const allThemes = useMemo(() => {
    const combined = { ...themes };
    customThemes.forEach(customTheme => {
      combined[customTheme.id] = customTheme;
    });
    return combined;
  }, [customThemes]);

  const theme = allThemes[currentTheme] || themes.light;
  const availableThemes = useMemo(() => Object.values(allThemes), [allThemes]);

  // Apply theme CSS variables to document root
  useEffect(() => {
    const root = document.documentElement;
    
    Object.entries(theme.colors).forEach(([key, value]) => {
      // Convert camelCase to kebab-case for CSS variables
      const cssVarName = `--color-${key.replace(/([A-Z])/g, '-$1').toLowerCase()}`;
      root.style.setProperty(cssVarName, value);
    });
    
    // Store theme preference
    localStorage.setItem('app-theme', currentTheme);
    
    // Add theme class to root for potential CSS-based targeting
    root.className = `theme-${currentTheme}`;
  }, [currentTheme, theme]);

  const setTheme = useCallback((themeId: string) => {
    if (allThemes[themeId]) {
      setCurrentTheme(themeId);
    }
  }, [allThemes]);

  const createCustomTheme = useCallback((theme: Theme) => {
    const newCustomThemes = [...customThemes, theme];
    setCustomThemes(newCustomThemes);
    saveCustomThemes(newCustomThemes);
  }, [customThemes]);

  const updateCustomTheme = useCallback((updatedTheme: Theme) => {
    const newCustomThemes = customThemes.map(t => 
      t.id === updatedTheme.id ? updatedTheme : t
    );
    setCustomThemes(newCustomThemes);
    saveCustomThemes(newCustomThemes);
  }, [customThemes]);

  const deleteCustomTheme = useCallback((themeId: string) => {
    const newCustomThemes = customThemes.filter(t => t.id !== themeId);
    setCustomThemes(newCustomThemes);
    saveCustomThemes(newCustomThemes);
    
    // If deleting the current theme, switch to light theme
    if (currentTheme === themeId) {
      setCurrentTheme('light');
    }
  }, [customThemes, currentTheme]);

  // Check if a theme is built-in (not custom)
  const isBuiltInTheme = useCallback((themeId: string): boolean => {
    return themeId in themes;
  }, []);

  // Check if a built-in theme has been modified (has a custom version)
  const isThemeModified = useCallback((themeId: string): boolean => {
    if (!(themeId in themes)) return false;
    return customThemes.some(t => t.id === themeId);
  }, [customThemes]);

  // Get the default (built-in) version of a theme
  const getDefaultTheme = useCallback((themeId: string): Theme | null => {
    return themes[themeId] || null;
  }, []);

  // Restore a modified built-in theme to its default values
  const restoreThemeToDefault = useCallback((themeId: string) => {
    if (!(themeId in themes)) {
      console.warn(`Cannot restore ${themeId}: not a built-in theme`);
      return;
    }

    // Remove the custom version (if it exists)
    const newCustomThemes = customThemes.filter(t => t.id !== themeId);
    setCustomThemes(newCustomThemes);
    saveCustomThemes(newCustomThemes);

    // If this was the current theme, force a re-render by temporarily switching themes
    if (currentTheme === themeId) {
      // Temporarily switch to light theme, then back to force re-render
      setCurrentTheme('light');
      setTimeout(() => {
        setCurrentTheme(themeId);
      }, 0);
    }
  }, [customThemes, currentTheme]);

  return (
    <ThemeContext.Provider value={{ 
      currentTheme, 
      theme, 
      setTheme, 
      availableThemes,
      customThemes,
      createCustomTheme,
      updateCustomTheme,
      deleteCustomTheme,
      isBuiltInTheme,
      isThemeModified,
      restoreThemeToDefault,
      getDefaultTheme
    }}>
      {children}
    </ThemeContext.Provider>
  );
};

